### ISSUE TITLE
Java Module Issue on Windows Build - v0.5.0.alpha7

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1094]
When building and launching from Windows with JDK 17.0.1, the following error occurs:

Nov 02, 2021 2:40:56 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @34129c78'
Exception in thread "main" java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x34129c78) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x34129c78
        at com.jidesoft.plaf.LookAndFeelFactory.getDefaultStyle(LookAndFeelFactory.java:539)
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
        at com.jidesoft.swing.JideSplitButton.updateUI(JideSplitButton.java:109)
        at java.desktop/javax.swing.JMenuItem.init(Unknown Source)
        at java.desktop/javax.swing.JMenuItem.<init>(Unknown Source)
        at java.desktop/javax.swing.JMenuItem.<init>(Unknown Source)
        at java.desktop/javax.swing.JMenu.<init>(Unknown Source)
        at com.jidesoft.swing.JideMenu.<init>(JideMenu.java:64)
        at com.jidesoft.swing.JideSplitButton.<init>(JideSplitButton.java:49)
        at io.github.dsheirer.module.decode.event.MessageActivityPanel$MessageHistoryButton.<init>(MessageActivityPanel.java:142)
        at io.github.dsheirer.module.decode.event.MessageActivityPanel$MessageManagementPanel.<init>(MessageActivityPanel.java:110)
        at io.github.dsheirer.module.decode.event.MessageActivityPanel.<init>(MessageActivityPanel.java:62)
        at io.github.dsheirer.channel.metadata.NowPlayingPanel.<init>(NowPlayingPanel.java:50)
        at io.github.dsheirer.controller.ControllerPanel.<init>(ControllerPanel.java:66)
        at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:194)
        at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:624)

**Comment by DSheirer** [comment]
To resolve, update gradle.build in the run{} block to add the export needed for windows:

--add-exports java.desktop/com.sun.java.swing.plaf.windows=com.jidesoft.plaf
