### ISSUE TITLE
Playlist Editor Blank - Linux aarch64 Build v0.5.0.alpha7

### ISSUE THREAD

**Issue by farewell-ladmin** [DSheirer/sdrtrunk#1095]
Not sure if this is something specific to aarch64/RPI4 but running into an issue with the alpha7 build on an RPi4 running Ubuntu 21.04.

Built using the Liberica Full JDK 17.0.1+12 from source. Program launches without any issue and recognizes the SDR but when I go to launch the Playlist Editor I get a blank screen with the following error.

`Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x7905a0b8) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x7905a0b8
	at org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:538)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
	at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.getGroupField(AliasItemEditor.java:1114)
	at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.getTextFieldPane(AliasItemEditor.java:989)
	at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.<init>(AliasItemEditor.java:180)
	at io.github.dsheirer.gui.playlist.alias.AliasConfigurationEditor.getAliasItemEditor(AliasConfigurationEditor.java:216)
	at io.github.dsheirer.gui.playlist.alias.AliasConfigurationEditor.<init>(AliasConfigurationEditor.java:121)
	at io.github.dsheirer.gui.playlist.alias.AliasEditor.getAliasConfigurationEditor(AliasEditor.java:106)
	at io.github.dsheirer.gui.playlist.alias.AliasEditor.getAliasConfigurationTab(AliasEditor.java:96)
	at io.github.dsheirer.gui.playlist.alias.AliasEditor.<init>(AliasEditor.java:57)
	at io.github.dsheirer.gui.playlist.PlaylistEditor.getAliasEditor(PlaylistEditor.java:225)
	at io.github.dsheirer.gui.playlist.PlaylistEditor.getAliasesTab(PlaylistEditor.java:215)
	at io.github.dsheirer.gui.playlist.PlaylistEditor.getTabPane(PlaylistEditor.java:203)
	at io.github.dsheirer.gui.playlist.PlaylistEditor.lambda$new$0(PlaylistEditor.java:96)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:833)
`
It looks like it creates the playlist xml file but it doesn't display anything.

I ended up compiling and running alpha6 on the RPi so it ended up being a non issue for me but wanted to raise it in case others are trying to compile alpha7 on an RPi and run into issues.

**Comment by DSheirer** [comment]
Closing.  Resolved in #1094
