### ISSUE TITLE
Playlist Editor blank, throwing exception upon opening

### ISSUE THREAD

**Issue by LordDonkey** [DSheirer/sdrtrunk#1121]
![20211129_142509_screen_capture](https://user-images.githubusercontent.com/52051804/143929916-0dd2b05c-9a4f-4144-aa22-ba1c08af8a40.png)

Upon opening the Playlist Editor, the following exception shows up in the console.

Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x11fc564b) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x11fc564b
        at org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:538)
        at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
        at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
        at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.getGroupField(AliasItemEditor.java:1117)
        at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.getTextFieldPane(AliasItemEditor.java:992)
        at io.github.dsheirer.gui.playlist.alias.AliasItemEditor.<init>(AliasItemEditor.java:180)
        at io.github.dsheirer.gui.playlist.alias.AliasConfigurationEditor.getAliasItemEditor(AliasConfigurationEditor.java:216)
        at io.github.dsheirer.gui.playlist.alias.AliasConfigurationEditor.<init>(AliasConfigurationEditor.java:119)
        at io.github.dsheirer.gui.playlist.alias.AliasEditor.getAliasConfigurationEditor(AliasEditor.java:106)
        at io.github.dsheirer.gui.playlist.alias.AliasEditor.getAliasConfigurationTab(AliasEditor.java:96)
        at io.github.dsheirer.gui.playlist.alias.AliasEditor.<init>(AliasEditor.java:57)
        at io.github.dsheirer.gui.playlist.PlaylistEditor.getAliasEditor(PlaylistEditor.java:225)
        at io.github.dsheirer.gui.playlist.PlaylistEditor.getAliasesTab(PlaylistEditor.java:215)
        at io.github.dsheirer.gui.playlist.PlaylistEditor.getTabPane(PlaylistEditor.java:203)
        at io.github.dsheirer.gui.playlist.PlaylistEditor.lambda$new$0(PlaylistEditor.java:96)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LordDonkey** [comment]
Resolved issue by installing the Oracle JDK rather than Azul or Liberica.
