### ISSUE TITLE
Build from latest commits causes OOM

### ISSUE THREAD

**Issue by davidmckenzie** [DSheirer/sdrtrunk#1135]
Previously using alpha 5, built from source to give the new NBFM features a go but seems to not be working right here. macOS Mojave on an older MBP. Liberica JDK.

```
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: Unknown module: javafx.base specified to --add-exports
15:15:35.472 INFO  i.g.d.icon.IconModel - loading icons file [/Users/x/SDRTrunk/settings/icons.xml]  [13MB/260MB 5%]
15:15:36.219 INFO  i.g.d.log.ApplicationLog - Application Log File: /Users/x/SDRTrunk/logs/sdrtrunk_app.log  [16MB/260MB 6%]
15:15:36.241 INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.5.0-alpha7  [17MB/260MB 6%]
15:15:36.241 INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 7.2  [17MB/260MB 6%]
15:15:36.241 INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2022-01-26T15:04:56.812+1100  [17MB/260MB 6%]
15:15:36.242 INFO  i.g.d.log.ApplicationLog - Build-JDK         : 17.0.2 (BellSoft 17.0.2+9-LTS  [17MB/260MB 6%]
15:15:36.242 INFO  i.g.d.log.ApplicationLog - Build OS          : Mac OS X (x86_64 10.14.3  [17MB/260MB 6%]
15:15:36.242 INFO  i.g.d.log.ApplicationLog -   [17MB/260MB 6%]
15:15:36.242 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [17MB/260MB 6%]
15:15:36.243 INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [17MB/260MB 6%]
15:15:36.243 INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [17MB/260MB 6%]
15:15:36.243 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [17MB/260MB 6%]
15:15:36.244 INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [17MB/260MB 6%]
15:15:36.244 INFO  i.g.d.log.ApplicationLog - Host OS Name:          Mac OS X  [17MB/260MB 6%]
15:15:36.244 INFO  i.g.d.log.ApplicationLog - Host OS Arch:          x86_64  [17MB/260MB 6%]
15:15:36.245 INFO  i.g.d.log.ApplicationLog - Host OS Version:       10.14.3  [17MB/260MB 6%]
15:15:36.245 INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        8  [17MB/260MB 6%]
15:15:36.245 INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  4 GB  [17MB/260MB 6%]
15:15:36.246 INFO  i.g.d.log.ApplicationLog - Storage Directories:  [17MB/260MB 6%]
15:15:36.246 INFO  i.g.d.log.ApplicationLog -  Application Root: /Users/x/SDRTrunk  [17MB/260MB 6%]
15:15:36.246 INFO  i.g.d.log.ApplicationLog -  Application Log:  /Users/x/SDRTrunk/logs  [17MB/260MB 6%]
15:15:36.247 INFO  i.g.d.log.ApplicationLog -  Event Log:        /Users/x/SDRTrunk/event_logs  [17MB/260MB 6%]
15:15:36.247 INFO  i.g.d.log.ApplicationLog -  Playlist:         /Users/x/SDRTrunk/playlist  [17MB/260MB 6%]
15:15:36.247 INFO  i.g.d.log.ApplicationLog -  Recordings:       /Users/x/SDRTrunk/recordings  [17MB/260MB 6%]
15:15:36.359 INFO  i.g.d.util.ThreadPool - Application thread pool created with [8] threads  [20MB/260MB 8%]
15:15:36.360 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /Users/x/SDRTrunk  [20MB/260MB 8%]
15:15:36.361 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/Users/x/SDRTrunk/SDRTrunk.properties]  [20MB/260MB 8%]
15:15:36.361 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/Users/x/SDRTrunk/SDRTrunk.properties]  [20MB/260MB 8%]
15:15:36.374 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [/Users/x/SDRTrunk/settings/settings.xml]  [21MB/260MB 8%]
15:15:36.427 INFO  i.g.d.s.r.RecordingSourceManager - RecordingSourceManager - discovered [0] recording configurations  [23MB/260MB 8%]
15:15:36.483 INFO  i.g.d.s.t.TunerManager - LibUSB API Version: 16777478  [23MB/260MB 9%]
15:15:36.484 INFO  i.g.d.s.t.TunerManager - LibUSB Version: 1.0.22.11312  [23MB/260MB 9%]
15:15:36.485 INFO  i.g.d.s.t.TunerManager - discovered [11] attached USB devices  [23MB/260MB 9%]
15:15:36.492 ERROR i.g.d.s.t.r.RTL2832TunerController - error while determining tuner type  [24MB/260MB 9%]
io.github.dsheirer.source.SourceException: couldn't claim usb interface [LIBUSB_ERROR_ACCESS]
	at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.claimInterface(RTL2832TunerController.java:204)
	at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.identifyTunerType(RTL2832TunerController.java:353)
	at io.github.dsheirer.source.tuner.TunerManager.initRTL2832Tuner(TunerManager.java:476)
	at io.github.dsheirer.source.tuner.TunerManager.initTuner(TunerManager.java:333)
	at io.github.dsheirer.source.tuner.TunerManager.initTuners(TunerManager.java:148)
	at io.github.dsheirer.source.tuner.TunerManager.<init>(TunerManager.java:79)
	at io.github.dsheirer.source.SourceManager.<init>(SourceManager.java:46)
	at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:167)
	at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:624)
15:15:36.502 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [0BDA:2838] Unknown Device - Class 0  [24MB/260MB 9%]
15:15:38.097 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2048000.0] providing [80] channels at [25600.0] Hz each  [26MB/260MB 10%]
15:15:38.237 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [0BDA:2838] LOADED: RTL2832 SDR/R820T 00000001 Max Rate:38400000 bps  [26MB/260MB 10%]
15:15:39.797 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2048000.0] providing [80] channels at [25600.0] Hz each  [26MB/260MB 10%]
15:15:39.948 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [0BDA:2838] LOADED: RTL2832 SDR/R820T 0011 Max Rate:38400000 bps  [26MB/260MB 10%]
15:15:39.949 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [1A40:0101] Hub Device  [26MB/260MB 10%]
15:15:39.949 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [05AC:8510] Miscellaneous Device  [26MB/260MB 10%]
15:15:39.950 INFO  i.g.d.s.t.TunerManager - USB Bus [29] Device [05AC:8286] Unknown Device - Class -1  [26MB/260MB 10%]
15:15:39.950 INFO  i.g.d.s.t.TunerManager - USB Bus [29] Device [05AC:0262] Unknown Device - Class 0  [26MB/260MB 10%]
15:15:39.950 INFO  i.g.d.s.t.TunerManager - USB Bus [29] Device [0A5C:4500] Hub Device  [26MB/260MB 10%]
15:15:39.951 INFO  i.g.d.s.t.TunerManager - USB Bus [29] Device [0424:2512] Hub Device  [26MB/260MB 10%]
15:15:39.951 INFO  i.g.d.s.t.TunerManager - USB Bus [29] Device [8087:0024] Hub Device  [26MB/260MB 10%]
15:15:39.951 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Device [8087:0024] Hub Device  [26MB/260MB 10%]
15:15:39.952 INFO  i.g.d.s.t.TunerManager - -------------------------------------------------------------  [26MB/260MB 10%]
15:15:39.952 INFO  i.g.d.s.t.TunerManager - USB Bus - Potential Maximum Data Rates  [27MB/260MB 10%]
15:15:39.952 INFO  i.g.d.s.t.TunerManager - USB Bus [26] Rate [76800000] bits per second  [27MB/260MB 10%]
Jan 26, 2022 3:15:40 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @548e6d58'
15:15:41.578 INFO  i.g.d.p.PlaylistManager - Loading playlist [/Users/x/SDRTrunk/playlist/default.xml]  [34MB/54MB 64%]
15:15:43.402 INFO  i.g.dsheirer.gui.SDRTrunk - starting main application gui  [27MB/54MB 50%]
15:15:44.192 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [NSW GRN - New England / Northern Tablelands] status: Connected  [45MB/84MB 54%]
15:15:45.974 INFO  i.g.d.c.c.ChannelAutoStartFrame - Starting [3] channels now - user invoked  [48MB/84MB 57%]
15:15:46.124 INFO  i.g.d.a.c.m.JmbeAudioModule - Loading JMBE library from [/Users/x/sdrtrunk/jmbe-1.0.5.jar]  [46MB/84MB 55%]
15:15:46.132 INFO  i.g.d.a.c.m.JmbeAudioModule - JMBE audio conversion library loaded: JMBE Audio Conversion Library v1.0.5  [46MB/84MB 55%]
15:15:46.132 INFO  i.g.d.a.c.m.ImbeAudioModule - JMBE audio conversion library IMBE CODEC successfully loaded - P25-1 audio will be available  [46MB/84MB 55%]
15:15:46.149 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2048000.0] providing [80] channels at [25600.0] Hz each  [47MB/84MB 56%]
15:15:46.172 INFO  i.g.d.s.t.u.USBMasterProcessor - Starting USB master processor thread  [50MB/84MB 60%]
15:19:29.109 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [NSW GRN - New England / Northern Tablelands] status: Disconnected  [3GB/4GB 99%]
15:20:09.979 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [NSW GRN - New England / Northern Tablelands] status: Disconnected  [3GB/4GB 99%]
15:20:16.281 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [NSW GRN - New England / Northern Tablelands] status: Connected  [3GB/4GB 99%]
15:21:47.517 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [NSW GRN - New England / Northern Tablelands] status: Disconnected  [3GB/4GB 99%]
15:22:40.169 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.math.BigDecimal$StringBuilderHelper.<init>(BigDecimal.java:3868)
	at java.base/java.math.BigDecimal.layoutChars(BigDecimal.java:3977)
	at java.base/java.math.BigDecimal.toString(BigDecimal.java:3383)
	at java.base/java.math.BigDecimal.floatValue(BigDecimal.java:3770)
	at java.base/java.lang.Math.fma(Math.java:1892)
	at io.github.dsheirer.dsp.filter.fir.real.RealFIRFilter2.filter(RealFIRFilter2.java:88)
	at io.github.dsheirer.dsp.filter.fir.complex.ComplexFIRFilter2.filterQuadrature(ComplexFIRFilter2.java:79)
	at io.github.dsheirer.dsp.filter.fir.complex.ComplexFIRFilter2.filter(ComplexFIRFilter2.java:123)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderC4FM.filter(P25P1DecoderC4FM.java:126)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderC4FM.receive(P25P1DecoderC4FM.java:104)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderC4FM.receive(P25P1DecoderC4FM.java:44)
	at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:42)
	at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:23)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.flush(ReusableComplexBufferAssembler.java:159)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:131)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:143)
	at io.github.dsheirer.dsp.filter.channelizer.output.TwoChannelOutputProcessor.process(TwoChannelOutputProcessor.java:117)
	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.processChannelResults(ChannelOutputProcessor.java:124)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.processSamples(PolyphaseChannelSource.java:248)
	at io.github.dsheirer.source.tuner.channel.TunerChannelSource$ScheduledIntervalProcessor.run(TunerChannelSource.java:319)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
15:23:13.465 ERROR i.g.d.d.f.c.ContinuousBufferProcessor - Error while dispatching buffers to listener  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
15:23:13.465 ERROR i.g.d.a.b.AudioStreamingBroadcaster - Error while processing audio streaming queue  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
15:24:12.453 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
^C15:24:12.453 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
15:24:38.475 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
15:24:36.571 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
15:24:41.523 ERROR i.g.d.s.t.u.USBTransferProcessor - [R820T 0011] - error while processing USB transfer buffers  [3GB/4GB 98%]
java.lang.OutOfMemoryError: Java heap space
```

System has two rtl-sdr.com dongles, monitoring 2 quiet p25 trunking systems and a very quiet p25 conventional system.

I noticed fans spinning as soon as the app starts, even before the channels are started, and the 'messages' tab was really really slow to populate. On alpha 5 it's putting out dozens of messages per second, on this build it's putting out maybe 1 or 2 per second max. The control channels did not register as working for a good few seconds after starting them.

**Comment by smyers119** [comment]
Duplicate #1137
