### ISSUE TITLE
0.5.0a7 freezes

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#1137]
Building from current sources. Main branch. Application freezes and consumes all CPU resources. No sound with codec. Hangs when an active voice channel appears on the P25p1 site.

The group has a slightly similar problem 
https://groups.google.com/g/sdrtrunk/c/zniv11A3G4Y
https://groups.google.com/g/sdrtrunk/c/yONugozI-F0

System: macOS Catalina 10.15.7
CPU: intel x64
JDK: Azul Zulu Builds of OpenJDK (17.0.2+8 Zulu: 17.32.13, x86 64-bit, macOS 10.14 or later)

```
18:23:52.172 INFO  i.g.d.a.c.m.ImbeAudioModule - JMBE audio conversion library IMBE CODEC successfully loaded - P25-1 audio will be available  [80MB/156MB 51%]
18:23:52.190 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [7000000,0] providing [280] channels at [25000,0] Hz each  [81MB/156MB 52%]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Timer-0"
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
18:25:11.417 ERROR i.g.d.s.t.c.TunerChannelSource - Error during heartbeat processing  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:25:11.417 ERROR i.g.d.s.t.c.TunerChannelSource - Error while processing samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:25:11.417 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:25:13.828 ERROR i.g.d.s.t.u.USBTransferProcessor - [HackRF 00000000-00000000-A32868DC-227A7F47] - error while processing USB transfer buffers  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:25:51.894 ERROR i.g.d.d.f.c.ContinuousBufferProcessor - Error while dispatching buffers to listener  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:03.999 ERROR i.g.d.d.f.c.ContinuousBufferProcessor - Error while dispatching buffers to listener  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:08.448 ERROR i.g.d.s.t.u.USBTransferProcessor - [HackRF 00000000-00000000-A32868DC-227A7F47] - error while processing USB transfer buffers  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:08.808 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:23.169 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:22.956 ERROR i.g.d.s.t.u.USBTransferProcessor - [HackRF 00000000-00000000-A32868DC-227A7F47] - error while processing USB transfer buffers  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:26:44.719 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 76%]
java.lang.IllegalStateException: User count is below zero.  This indicates that this buffer's decrement user count was invoked by more than the expected user count
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.recycle(AbstractReusableBuffer.java:119)
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.decrementUserCount(AbstractReusableBuffer.java:100)
	at io.github.dsheirer.dsp.filter.channelizer.ComplexPolyphaseChannelizerM2.receive(ComplexPolyphaseChannelizerM2.java:234)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:607)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:568)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor.process(ContinuousBufferProcessor.java:189)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor$Processor.run(ContinuousBufferProcessor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:26:44.719 ERROR i.g.d.d.f.c.ContinuousBufferProcessor - Error while dispatching buffers to listener  [3GB/4GB 76%]
java.lang.IllegalStateException: User count is below zero.  This indicates that this buffer's decrement user count was invoked by more than the expected user count
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.recycle(AbstractReusableBuffer.java:119)
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.decrementUserCount(AbstractReusableBuffer.java:100)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:620)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:568)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor.process(ContinuousBufferProcessor.java:189)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor$Processor.run(ContinuousBufferProcessor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
18:27:14.975 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:14.975 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Java2D Disposer" java.lang.OutOfMemoryError: Java heap space
18:27:19.254 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:28.071 ERROR i.g.d.d.f.c.PolyphaseChannelManager - Error  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:28.432 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:29.162 ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:29.162 ERROR i.g.d.s.t.u.USBTransferProcessor - [HackRF 00000000-00000000-A32868DC-227A7F47] - error while processing USB transfer buffers  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:28.432 ERROR i.g.d.s.t.u.USBMasterProcessor - Error while processing LibUSB timeout events  [3GB/4GB 99%]
java.lang.OutOfMemoryError: Java heap space
18:27:29.495 ERROR i.g.d.d.f.c.ContinuousBufferProcessor - Error while dispatching buffers to listener  [3GB/4GB 99%]
java.lang.IllegalStateException: User count is below zero.  This indicates that this buffer's decrement user count was invoked by more than the expected user count
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.recycle(AbstractReusableBuffer.java:119)
	at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.decrementUserCount(AbstractReusableBuffer.java:100)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:620)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$BufferSourceEventMonitor.receive(PolyphaseChannelManager.java:568)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor.process(ContinuousBufferProcessor.java:189)
	at io.github.dsheirer.dsp.filter.channelizer.ContinuousBufferProcessor$Processor.run(ContinuousBufferProcessor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

```

**Comment by DSheirer** [comment]
Closing.  OBE.
