### ISSUE TITLE
Airspy Error Handling Issue

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1234]
Error in Airspy tuner while streaming and then automatic removal causes infinite loop in error handler due to concurrent modification.

09:42:56.773 WARN  i.g.d.c.c.ChannelProcessingManager - Tuner removal detected - stopping channel [TRAFFIC]  [470MB/1GB 45%]
Exception in thread "sdrtrunk polyphase channel" java.lang.StackOverflowError
        at java.base/java.util.concurrent.ConcurrentHashMap$EntrySetView.iterator(Unknown Source)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager$ChannelSourceEventErrorListener.receive(ChannelProcessingManager.java:733)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager$ChannelSourceEventErrorListener.receive(ChannelProcessingManager.java:719)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:190)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:62)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastConsumerSourceEvent(TunerChannelSource.java:236)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.process(TunerChannelSource.java:194)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:51)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:25)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:190)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:62)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastConsumerSourceEvent(TunerChannelSource.java:236)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.process(TunerChannelSource.java:194)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:51)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:25)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:190)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:62)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastConsumerSourceEvent(TunerChannelSource.java:236)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource.process(TunerChannelSource.java:194)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:51)
        at io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:25)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:190)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:62)

**Comment by DSheirer** [comment]
Could not duplicate.  This error existed previously and was fixed in a more recent update.
