### ISSUE TITLE
Cannot use recording tuners, Filter Design Errors

### ISSUE THREAD

**Issue by Nokoa** [DSheirer/sdrtrunk#1276]
Getting the following error while attempting to start a channel for a currently loaded and enabled recording tuner, within the mhz range.

```
22:45:14.596 ERROR i.g.d.d.f.f.r.RemezFIRFilterDesigner - Filter design error - couldn't find extremal indices at count [1] try changing filter order up/down from [1423]  [146MB/178MB 82%]
22:45:14.599 ERROR i.g.d.util.ThreadPool - Error while executing runnable in scheduled thread pool [sdrtrunk cached thread 1]  [146MB/178MB 82%]
java.lang.IllegalStateException: Couldn't design a DMR baseband filter for sample rate: 1024000.0
        at io.github.dsheirer.module.decode.dmr.DMRDecoder.getBasebandFilter(DMRDecoder.java:197)
        at io.github.dsheirer.module.decode.dmr.DMRDecoder.setSampleRate(DMRDecoder.java:119)
        at io.github.dsheirer.module.decode.dmr.DMRDecoder.process(DMRDecoder.java:213)
        at io.github.dsheirer.module.decode.dmr.DMRDecoder.lambda$getSourceEventListener$0(DMRDecoder.java:311)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:151)
        at io.github.dsheirer.module.ProcessingChain.start(ProcessingChain.java:635)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.startProcessing(ChannelProcessingManager.java:516)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.start(ChannelProcessingManager.java:303)
        at io.github.dsheirer.gui.playlist.channel.ChannelConfigurationEditor.lambda$getPlayButton$3(ChannelConfigurationEditor.java:372)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Nokoa** [comment]
note that at the time of recording, tuner was setup to a lower sample rate, and not to its fullest.

**Comment by Nokoa** [comment]
In the RecordingTuner.java file in its constructor 
```
      if (getTunerController().getCurrentSampleRate() < 100000.0d ) {
            setChannelSourceManager(new PassThroughSourceManager(getTunerController()));
        } 
```

The sample rate is 0 at the beginning, so that conditional statement is true and it will generate a passThroughSource channel rather than the Polyphase or Heterodyne source channels.
