### ISSUE TITLE
Java errors showing up in terminal window running sdrtrunk but not in sdrtrunk log

### ISSUE THREAD

**Issue by wmg819** [DSheirer/sdrtrunk#1278]
Strange error messages have started popping up in the SDRTrunk log and in the terminal window used to start the program. This is on a system running Ubuntu 22.04, the system processor is an AMDRyzen 5 2400g with radeon vega graphics on 8 cpu core and 32Gib Ram. I didn't notice this issue when running Ubuntu 20.04 on the same system. 

Here are the two logs
First the terminal window activity
19:44:38.746 INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.5.0-beta3  [5MB/472MB 1%]
19:44:38.746 INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 7.4.2  [5MB/472MB 1%]
19:44:38.746 INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2022-05-04T14:55:06.134-0400  [5MB/472MB 1%]
19:44:38.747 INFO  i.g.d.log.ApplicationLog - Build-JDK         : 18.0.1 (BellSoft 18.0.1+12  [5MB/472MB 1%]
19:44:38.747 INFO  i.g.d.log.ApplicationLog - Build OS          : Linux (amd64 5.13.0-40-generic  [5MB/472MB 1%]
19:44:38.747 INFO  i.g.d.log.ApplicationLog -   [5MB/472MB 1%]
19:44:38.748 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/472MB 1%]
19:44:38.748 INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [5MB/472MB 1%]
19:44:38.748 INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [5MB/472MB 1%]
19:44:38.748 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/472MB 1%]
19:44:38.749 INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [5MB/472MB 1%]
19:44:38.749 INFO  i.g.d.log.ApplicationLog - Host OS Name:          Linux  [5MB/472MB 1%]
19:44:38.749 INFO  i.g.d.log.ApplicationLog - Host OS Arch:          amd64  [5MB/472MB 1%]
19:44:38.750 INFO  i.g.d.log.ApplicationLog - Host OS Version:       5.15.0-40-generic  [5MB/472MB 1%]
19:44:38.750 INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        8  [5MB/472MB 1%]
19:44:38.750 INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  7 GB  [5MB/472MB 1%]
19:44:38.751 INFO  i.g.d.log.ApplicationLog - Storage Directories:  [5MB/472MB 1%]
19:44:38.751 INFO  i.g.d.log.ApplicationLog -  Application Root: /home/xx/SDRTrunk  [5MB/472MB 1%]
19:44:38.751 INFO  i.g.d.log.ApplicationLog -  Application Log:  /home/xx/SDRTrunk/logs  [5MB/472MB 1%]
19:44:38.752 INFO  i.g.d.log.ApplicationLog -  Event Log:        /home/xx/SDRTrunk/event_logs  [5MB/472MB 1%]
19:44:38.752 INFO  i.g.d.log.ApplicationLog -  Playlist:         /home/xx/SDRTrunk/playlist  [5MB/472MB 1%]
19:44:38.753 INFO  i.g.d.log.ApplicationLog -  Recordings:       /home/xx/SDRTrunk/recordings  [5MB/472MB 1%]
19:44:38.843 INFO  i.g.d.util.ThreadPool - Application thread pool created SCHEDULED and CACHED executors threads  [8MB/472MB 1%]
19:44:38.843 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /home/xx/SDRTrunk  [8MB/472MB 1%]
19:44:38.844 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/home/xx/SDRTrunk/SDRTrunk.properties]  [8MB/472MB 1%]
19:44:38.844 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/home/xx/SDRTrunk/SDRTrunk.properties]  [8MB/472MB 1%]
19:44:39.089 INFO  i.g.d.s.t.m.TunerManager - Discovering tuners ...  [14MB/56MB 25%]
19:44:39.097 INFO  i.g.d.s.t.m.TunerManager - LibUsb API Version: 1.0.262  [14MB/56MB 26%]
19:44:39.098 INFO  i.g.d.s.t.m.TunerManager - LibUsb Version: 1.0.22.11312  [14MB/56MB 26%]
19:44:39.102 INFO  i.g.d.s.t.m.TunerManager - LibUsb - discovered [14] potential usb devices  [14MB/56MB 26%]
19:44:39.107 INFO  i.g.d.s.t.m.TunerManager - Discovered tuner at USB Bus [3] Port [3.4] Tuner Class [RTL-2832]  [14MB/56MB 26%]
19:44:39.111 INFO  i.g.d.s.t.m.TunerManager - Discovered tuner at USB Bus [3] Port [3.3] Tuner Class [RTL-2832]  [14MB/56MB 26%]
19:44:39.111 INFO  i.g.d.s.t.m.TunerManager - Discovered tuner at USB Bus [3] Port [3.1] Tuner Class [RTL-2832]  [14MB/56MB 26%]
19:44:39.113 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.4 - Added / Starting ...  [14MB/56MB 26%]
19:44:40.281 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [17MB/56MB 31%]
19:44:40.283 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.4 - Applying Tuner Configuration  [17MB/56MB 31%]
19:44:40.508 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.3 - Added / Starting ...  [18MB/56MB 32%]
19:44:41.633 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [18MB/56MB 32%]
19:44:41.633 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.3 - Applying Tuner Configuration  [18MB/56MB 32%]
19:44:41.853 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.1 - Added / Starting ...  [18MB/56MB 33%]
19:44:42.987 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [19MB/56MB 35%]
19:44:42.987 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.1 - Applying Tuner Configuration  [19MB/56MB 35%]
19:44:43.208 INFO  i.g.d.s.t.m.TunerManager - LibUsb - starting HotPlug detection  [20MB/56MB 35%]
19:44:43.216 INFO  i.g.d.s.t.m.TunerManager - Tuner plug-in detected at USB Bus [3] Port [4] Tuner Class [RTL-2832]  [20MB/56MB 35%]
19:44:43.217 INFO  i.g.d.s.t.m.TunerManager - Tuner plug-in detected at USB Bus [3] Port [3] Tuner Class [RTL-2832]  [20MB/56MB 35%]
19:44:43.217 INFO  i.g.d.s.t.m.TunerManager - Tuner plug-in detected at USB Bus [3] Port [1] Tuner Class [RTL-2832]  [20MB/56MB 35%]
19:44:43.221 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [/home/xx/SDRTrunk/settings/settings.xml]  [20MB/56MB 36%]
19:44:43.618 WARN  i.g.d.v.VectorUtilities - CPU supports maximum SIMD instructions of Species[float, 8, S_256_BIT]  [33MB/56MB 59%]
19:44:44.303 INFO  i.g.d.p.PlaylistManager - Loading playlist [/home/xx/SDRTrunk/playlist/default.xml]  [18MB/56MB 33%]
19:44:44.396 INFO  i.g.dsheirer.gui.SDRTrunk - starting main application gui  [22MB/56MB 40%]
19:44:47.377 INFO  i.g.d.c.c.ChannelAutoStartFrame - Starting [1] channels now - user invoked  [23MB/56MB 42%]
19:44:47.423 INFO  i.g.d.a.c.m.JmbeAudioModule - Loading JMBE library from [/home/xx/SDRTrunk/jmbe/jmbe-1.0.9.jar]  [26MB/56MB 47%]
19:44:47.432 INFO  i.g.d.a.c.m.JmbeAudioModule - JMBE audio conversion library loaded: JMBE Audio Conversion Library v1.0.9  [26MB/56MB 47%]
19:44:47.433 INFO  i.g.d.a.c.m.ImbeAudioModule - JMBE audio conversion library IMBE CODEC successfully loaded - P25-1 audio will be available  [26MB/56MB 47%]
19:44:47.448 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [27MB/56MB 49%]
19:44:54.413 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [122MB/264MB 46%]
19:45:24.133 INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [9.3]  [264MB/464MB 56%]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "modelIndex" because "this.viewToModel[<parameter1>]" is null
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.getValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.prepareRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at java.desktop/javax.swing.plaf.ComponentUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
19:50:59.133 INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [8.9]  [148MB/464MB 32%]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "modelIndex" because "this.viewToModel[<parameter1>]" is null
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.getValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.prepareRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at java.desktop/javax.swing.plaf.ComponentUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
19:55:14.133 INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [8.4]  [293MB/464MB 63%]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "modelIndex" because "this.viewToModel[<parameter1>]" is null
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.convertRowIndexToModel(Unknown Source)
	at java.desktop/javax.swing.JTable.getValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.prepareRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at java.desktop/javax.swing.plaf.ComponentUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
20:05:54.133 INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [7.9]  [232MB/496MB 46%]
20:09:59.133 INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [7.4]  [207MB/496MB 41%]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

And here's the SDRTrunk log which seems normal
20220627 194411.686 [AWT-EventQueue-0] INFO  i.github.dsheirer.gui.SDRTrunk - Shutdown complete.  [316MB/488MB 64%]
20220627 194411.686 [AWT-EventQueue-0] INFO  i.g.d.log.ApplicationLog - Stopping application logging  [316MB/488MB 64%]
20220627 194438.746 [main] INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.5.0-beta3  [5MB/472MB 1%]
20220627 194438.746 [main] INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 7.4.2  [5MB/472MB 1%]
20220627 194438.746 [main] INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2022-05-04T14:55:06.134-0400  [5MB/472MB 1%]
20220627 194438.747 [main] INFO  i.g.d.log.ApplicationLog - Build-JDK         : 18.0.1 (BellSoft 18.0.1+12  [5MB/472MB 1%]
20220627 194438.747 [main] INFO  i.g.d.log.ApplicationLog - Build OS          : Linux (amd64 5.13.0-40-generic  [5MB/472MB 1%]
20220627 194438.747 [main] INFO  i.g.d.log.ApplicationLog -   [5MB/472MB 1%]
20220627 194438.748 [main] INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/472MB 1%]
20220627 194438.748 [main] INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [5MB/472MB 1%]
20220627 194438.748 [main] INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [5MB/472MB 1%]
20220627 194438.748 [main] INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/472MB 1%]
20220627 194438.749 [main] INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [5MB/472MB 1%]
20220627 194438.749 [main] INFO  i.g.d.log.ApplicationLog - Host OS Name:          Linux  [5MB/472MB 1%]
20220627 194438.749 [main] INFO  i.g.d.log.ApplicationLog - Host OS Arch:          amd64  [5MB/472MB 1%]
20220627 194438.750 [main] INFO  i.g.d.log.ApplicationLog - Host OS Version:       5.15.0-40-generic  [5MB/472MB 1%]
20220627 194438.750 [main] INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        8  [5MB/472MB 1%]
20220627 194438.750 [main] INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  7 GB  [5MB/472MB 1%]
20220627 194438.751 [main] INFO  i.g.d.log.ApplicationLog - Storage Directories:  [5MB/472MB 1%]
20220627 194438.751 [main] INFO  i.g.d.log.ApplicationLog -  Application Root: /home/xx/SDRTrunk  [5MB/472MB 1%]
20220627 194438.751 [main] INFO  i.g.d.log.ApplicationLog -  Application Log:  /home/xx/SDRTrunk/logs  [5MB/472MB 1%]
20220627 194438.752 [main] INFO  i.g.d.log.ApplicationLog -  Event Log:        /home/xx/SDRTrunk/event_logs  [5MB/472MB 1%]
20220627 194438.752 [main] INFO  i.g.d.log.ApplicationLog -  Playlist:         /home/xx/SDRTrunk/playlist  [5MB/472MB 1%]
20220627 194438.753 [main] INFO  i.g.d.log.ApplicationLog -  Recordings:       /home/xx/SDRTrunk/recordings  [5MB/472MB 1%]
20220627 194438.843 [main] INFO  i.g.dsheirer.util.ThreadPool - Application thread pool created SCHEDULED and CACHED executors threads  [8MB/472MB 1%]
20220627 194438.843 [main] INFO  i.github.dsheirer.gui.SDRTrunk - Home path: /home/xx/SDRTrunk  [8MB/472MB 1%]
20220627 194438.844 [main] INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/home/xx/SDRTrunk/SDRTrunk.properties]  [8MB/472MB 1%]
20220627 194438.844 [main] INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/home/xx/SDRTrunk/SDRTrunk.properties]  [8MB/472MB 1%]
20220627 194439.089 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovering tuners ...  [14MB/56MB 25%]
20220627 194439.097 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb API Version: 1.0.262  [14MB/56MB 26%]
20220627 194439.098 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb Version: 1.0.22.11312  [14MB/56MB 26%]
20220627 194439.102 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb - discovered [14] potential usb devices  [14MB/56MB 26%]
20220627 194439.107 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [3] Port [3.4] Tuner Class [RTL-2832]  [14MB/56MB 26%]
20220627 194439.111 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [3] Port [3.3] Tuner Class [RTL-2832]  [14MB/56MB 26%]
20220627 194439.111 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [3] Port [3.1] Tuner Class [RTL-2832]  [14MB/56MB 26%]
20220627 194439.113 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.4 - Added / Starting ...  [14MB/56MB 26%]
20220627 194440.281 [main] INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [17MB/56MB 31%]
20220627 194440.283 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.4 - Applying Tuner Configuration  [17MB/56MB 31%]
20220627 194440.508 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.3 - Added / Starting ...  [18MB/56MB 32%]
20220627 194441.633 [main] INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [18MB/56MB 32%]
20220627 194441.633 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.3 - Applying Tuner Configuration  [18MB/56MB 32%]
20220627 194441.853 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.1 - Added / Starting ...  [18MB/56MB 33%]
20220627 194442.987 [main] INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [19MB/56MB 35%]
20220627 194442.987 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:3 Port:3.1 - Applying Tuner Configuration  [19MB/56MB 35%]
20220627 194443.208 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb - starting HotPlug detection  [20MB/56MB 35%]
20220627 194443.216 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner plug-in detected at USB Bus [3] Port [4] Tuner Class [RTL-2832]  [20MB/56MB 35%]
20220627 194443.217 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner plug-in detected at USB Bus [3] Port [3] Tuner Class [RTL-2832]  [20MB/56MB 35%]
20220627 194443.217 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner plug-in detected at USB Bus [3] Port [1] Tuner Class [RTL-2832]  [20MB/56MB 35%]
20220627 194443.221 [main] INFO  i.g.d.settings.SettingsManager - SettingsManager - loading settings file [/home/wg/SDRTrunk/settings/settings.xml]  [20MB/56MB 36%]
20220627 194443.618 [main] WARN  i.g.d.vector.VectorUtilities - CPU supports maximum SIMD instructions of Species[float, 8, S_256_BIT]  [33MB/56MB 59%]
20220627 194444.303 [main] INFO  i.g.d.playlist.PlaylistManager - Loading playlist [/home/xx/SDRTrunk/playlist/default.xml]  [18MB/56MB 33%]
20220627 194444.396 [main] INFO  i.github.dsheirer.gui.SDRTrunk - starting main application gui  [22MB/56MB 40%]
20220627 194447.377 [AWT-EventQueue-0] INFO  i.g.d.c.c.ChannelAutoStartFrame - Starting [1] channels now - user invoked  [23MB/56MB 42%]
20220627 194447.423 [AWT-EventQueue-0] INFO  i.g.d.a.c.mbe.JmbeAudioModule - Loading JMBE library from [/home/xx/SDRTrunk/jmbe/jmbe-1.0.9.jar]  [26MB/56MB 47%]
20220627 194447.432 [AWT-EventQueue-0] INFO  i.g.d.a.c.mbe.JmbeAudioModule - JMBE audio conversion library loaded: JMBE Audio Conversion Library v1.0.9  [26MB/56MB 47%]
20220627 194447.433 [AWT-EventQueue-0] INFO  i.g.d.a.c.mbe.ImbeAudioModule - JMBE audio conversion library IMBE CODEC successfully loaded - P25-1 audio will be available  [26MB/56MB 47%]
20220627 194447.448 [AWT-EventQueue-0] INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [27MB/56MB 49%]
20220627 194454.413 [sdrtrunk polyphase channel] INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [2400000.0] providing [96] channels at [25000.0] Hz each  [122MB/264MB 46%]
20220627 194524.133 [sdrtrunk scheduled thread 1] INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [9.3]  [264MB/464MB 56%]
20220627 195059.133 [sdrtrunk scheduled thread 1] INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [8.9]  [148MB/464MB 32%]
20220627 195514.133 [sdrtrunk scheduled thread 2] INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [8.4]  [293MB/464MB 63%]
20220627 200554.133 [sdrtrunk scheduled thread 2] INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [7.9]  [232MB/496MB 46%]
20220627 200959.133 [sdrtrunk scheduled thread 2] INFO  i.g.d.s.t.m.FrequencyErrorCorrectionManager - Auto-Correcting Tuner PPM to [7.4]  [207MB/496MB 41%]

Can anyone shed light on the errors?

**Comment by wmg819** [comment]
Issue seems to have been resolved by installing JRE and JDK which wasn't in the Ubuntu upgrade package. SDRTrunk running for 24 hrs without further issues logging and recording 9,189 calls in that time frame on the P25 system I'm  monitoring.

**Comment by wmg819** [comment]
Issue seems to have been resolved by installing JRE and JDK which wasn't in the Ubuntu upgrade package. SDRTrunk running for 24 hrs without further issues logging and recording 9,189 calls in that time frame on the P25 system I'm monitoring.
