### ISSUE TITLE
Radio Reference import error - specific to single system

### ISSUE THREAD

**Issue by dblalock1** [DSheirer/sdrtrunk#1312]
Under US --> Georgia --> Liberty --> Southeast Georgia Regional Radio Network

I've tried all of the counties that this system covers and the 'Service Unavailable' pop-up is thrown. Other trunked systems in the same counties import without issue.  I was able to import this system successfully about a year ago, so suspect something with the site or talk group data from Radio Reference is causing an issue with parsing. I've looked over the talk group and site data for  data errors, but am not seeing anything obvious.

Java output when the issue is triggered:

_13:46:43.091 ERROR i.g.d.g.p.r.SystemEditor - Error retrieving system information  [190MB/210MB 90%]
io.github.dsheirer.rrapi.RadioReferenceException: Error
	at io.github.dsheirer.rrapi.RadioReferenceService.submitSync(RadioReferenceService.java:1201)
	at io.github.dsheirer.rrapi.RadioReferenceService.getCountyInfo(RadioReferenceService.java:357)
	at io.github.dsheirer.service.radioreference.CachingRadioReferenceService.access$801(CachingRadioReferenceService.java:44)
	at io.github.dsheirer.service.radioreference.CachingRadioReferenceService.getCountyInfo(CachingRadioReferenceService.java:164)
	at io.github.dsheirer.gui.playlist.radioreference.SystemEditor.lambda$setSystem$5(SystemEditor.java:296)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)_

Link to RR system page: [https://www.radioreference.com/db/sid/6694](https://www.radioreference.com/db/sid/6694)

**Comment by DSheirer** [comment]
This system: https://www.radioreference.com/db/sid/6694

Site: '1.9' has a county ID of 0 and this is causing an error.  Update the code to ignore the call to get CountyInfo for sites that don't have a county ID.
