### ISSUE TITLE
Broadcastify feeds constantly disconnecting (Version 0.5.0 Beta 7)

### ISSUE THREAD

**Issue by zacharyfleck** [DSheirer/sdrtrunk#1373]
All BCFY feeds are disconnecting on a regular basis. See attached image. This issue does not occur on earlier versions. This is not an internet issue.

@doug-hoffman - I experienced this when I tried to manually build your changes from your fork about a month ago. I'm wondering if perhaps it has something to do with the stream settings and how the non-silence is generated?

<img width="367" alt="Screenshot 2022-12-21 at 10 26 52 AM" src="https://user-images.githubusercontent.com/87536651/208954957-95eb17f6-5764-4285-9970-f39a06cc06be.png">

**Comment by doug-hoffman** [comment]
FWIW, one of my feeds on beta 3 with #1244:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/58886678/208955768-fb9288e3-9ec0-40a7-a000-40ad36660795.png">

<img width="196" alt="image" src="https://user-images.githubusercontent.com/58886678/208956875-ea9b3213-a411-4ca5-9195-a14fae86d59e.png">

I've not used beta 7 in production yet. I'll give it a spin and see.

**Comment by doug-hoffman** [comment]
16kbps/8kHz

<img width="516" alt="image" src="https://user-images.githubusercontent.com/58886678/208958717-6f33909e-3245-4bb0-b3ea-4d318496f7cf.png">

**Comment by zacharyfleck** [comment]
Ok. Mine varies from that. Wonder if that's somehow related. I'm at 32kbps/22050kHz

**Comment by doug-hoffman** [comment]
My BCFY feeds have been stable on beta 7 for about 45 minutes.

I'm seeing issues with 32kbps/22.05kHz to a local icecast-2.4.4 server:

```
2022-12-21 12:15:26.624 ERROR i.g.d.a.b.AudioStreamingBroadcaster - Error while processing audio streaming queue  [925MB/1GB 70%]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at io.github.dsheirer.audio.convert.MP3Header.getMPEGVersion(MP3Header.java:60)
        at io.github.dsheirer.audio.convert.MP3Header.getFrameSamples(MP3Header.java:125)
        at io.github.dsheirer.audio.convert.MP3Header.getFrameDuration(MP3Header.java:157)
        at io.github.dsheirer.audio.convert.MP3AudioFrames.getCurrentFrameDuration(MP3AudioFrames.java:43)
        at io.github.dsheirer.audio.broadcast.AudioStreamingBroadcaster$RecordingQueueProcessor.run(AudioStreamingBroadcaster.java:302)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

32kbps/16kHz and 32kbps/8kHz seem fine.

I'll dig into this further this evening and see if I can figure out what's going on.

**Comment by doug-hoffman** [comment]
I identified the cause of the error above. I believe that should also resolve your issue with BCFY.
