### ISSUE TITLE
Icecast HTTP Protocol Error On Radio Reference Service HTTP 1.0 403 Error

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1380]
This may be an issue that the HTTP handler does not have HTTP 1.0 message parsing available.

2022-12-24 05:19:44.391 ERROR i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - HTTP protocol decoder error  [38MB/68MB 56%]
org.apache.mina.filter.codec.ProtocolDecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (Hexdump: 48 54 54 50 2F 31 2E 30 20 34 30 33 20 46 6F 72 62 69 64 64 65 6E 0D 0A 53 65 72 76 65 72 3A 20 49 63 65 63 61 73 74 20 32 2E 34 2E 34 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 43 6C 6F 73 65 0D 0A 44 61 74 65 3A 20 53 61 74 2C 20 32 34 20 44 65 63 20 32 30 32 32 20 31 30 3A 31 39 3A 34 34 20 47 4D 54 0D 0A 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 74 65 78 74 2F 70 6C 61 69 6E 3B 20 63 68 61 72 73 65 74 3D 75 74 66 2D 38 0D 0A 43 61 63 68 65 2D 43 6F 6E 74 72 6F 6C 3A 20 6E 6F 2D 63 61 63 68 65 2C 20 6E 6F 2D 73 74 6F 72 65 0D 0A 45 78 70 69 72 65 73 3A 20 4D 6F 6E 2C 20 32 36 20 4A 75 6C 20 31 39 39 37 20 30 35 3A 30 30 3A 30 30 20 47 4D 54 0D 0A 50 72 61 67 6D 61 3A 20 6E 6F 2D 63 61 63 68 65 0D 0A 41 63 63 65 73 73 2D 43 6F 6E 74 72 6F 6C 2D 41 6C 6C 6F 77 2D 4F 72 69 67 69 6E 3A 20 2A 0D 0A 0D 0A 4D 6F 75 6E 74 70 6F 69 6E 74 20 69 6E 20 75 73 65)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:255)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:122)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:643)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:539)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$1200(AbstractPollingIoProcessor.java:68)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1224)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1213)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:683)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.apache.mina.http.HttpClientDecoder.parseHttpReponseHead(HttpClientDecoder.java:242)
	at org.apache.mina.http.HttpClientDecoder.decode(HttpClientDecoder.java:114)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:247)
	... 15 common frames omitted

**Comment by DSheirer** [comment]
Debug logger enabled:


```
2022-12-24 05:35:30.978 INFO  i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - CREATED  [32MB/68MB 47%]
2022-12-24 05:35:30.978 INFO  i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - OPENED  [32MB/68MB 47%]
2022-12-24 05:35:30.979 INFO  i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - SENT: HTTP REQUEST METHOD: PUT
VERSION: HTTP/1.1
PATH: /stream
QUERY:
--- HEADER --- 
Authorization:Basic c291cmNlOmRlbm55
ice-genre:My Genre
Accept:*/*
ice-name:Local
ice-audio-info:samplerate=8000;quality=7;channels=1
User-Agent:sdrtrunk
ice-public:0
ice-bitrate:16
ice-description:Denny's Local Icecast2
ice-url:http://localhost:8000
icy-metaint:2000
Content-Type:audio/mpeg
--- PARAMETERS --- 
  [32MB/68MB 47%]
2022-12-24 05:35:30.983 INFO  i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - RECEIVED: HeapBuffer@4d9c6176[pos=0 lim=288 cap=2048: 48 54 54 50 2F 31 2E 30 20 34 30 33 20 46 6F 72]  [32MB/68MB 47%]
2022-12-24 05:35:30.984 ERROR i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - HTTP protocol decoder error  [32MB/68MB 47%]
org.apache.mina.filter.codec.ProtocolDecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (Hexdump: 48 54 54 50 2F 31 2E 30 20 34 30 33 20 46 6F 72 62 69 64 64 65 6E 0D 0A 53 65 72 76 65 72 3A 20 49 63 65 63 61 73 74 20 32 2E 34 2E 34 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 43 6C 6F 73 65 0D 0A 44 61 74 65 3A 20 53 61 74 2C 20 32 34 20 44 65 63 20 32 30 32 32 20 31 30 3A 33 35 3A 33 30 20 47 4D 54 0D 0A 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 74 65 78 74 2F 70 6C 61 69 6E 3B 20 63 68 61 72 73 65 74 3D 75 74 66 2D 38 0D 0A 43 61 63 68 65 2D 43 6F 6E 74 72 6F 6C 3A 20 6E 6F 2D 63 61 63 68 65 2C 20 6E 6F 2D 73 74 6F 72 65 0D 0A 45 78 70 69 72 65 73 3A 20 4D 6F 6E 2C 20 32 36 20 4A 75 6C 20 31 39 39 37 20 30 35 3A 30 30 3A 30 30 20 47 4D 54 0D 0A 50 72 61 67 6D 61 3A 20 6E 6F 2D 63 61 63 68 65 0D 0A 41 63 63 65 73 73 2D 43 6F 6E 74 72 6F 6C 2D 41 6C 6C 6F 77 2D 4F 72 69 67 69 6E 3A 20 2A 0D 0A 0D 0A 4D 6F 75 6E 74 70 6F 69 6E 74 20 69 6E 20 75 73 65)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:255)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
	at org.apache.mina.filter.logging.LoggingFilter.messageReceived(LoggingFilter.java:216)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:122)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:643)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:539)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$1200(AbstractPollingIoProcessor.java:68)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1224)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1213)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:683)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.apache.mina.http.HttpClientDecoder.parseHttpReponseHead(HttpClientDecoder.java:242)
	at org.apache.mina.http.HttpClientDecoder.decode(HttpClientDecoder.java:114)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:247)
	... 19 common frames omitted
2022-12-24 05:35:30.985 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [Local] status: Disconnected  [32MB/68MB 47%]
2022-12-24 05:35:30.986 INFO  i.g.d.a.b.i.IcecastHTTPAudioBroadcaster - CLOSED  [32MB/68MB 47%]
2022-12-24 05:35:32.836 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [SDRTrunk Test Feed #1] status: Disconnected  [38MB/76MB 51%]
2022-12-24 05:35:32.866 INFO  i.g.d.a.b.AudioStreamingBroadcaster - [SDRTrunk Test Feed #2] status: Disconnected  [38MB/76MB 51%]


```
