### ISSUE TITLE
Unable to initialize/start streaming for RSP Device

### ISSUE THREAD

**Issue by jamren01** [DSheirer/sdrtrunk#1503]
I am running off from the latest master branch, post commit 1500. When I returned to the computer today I had a large ratio of upload errors compared to the number streamed. The following message in the terminal window. Please advise if I can provide more detailed information or logs.

> 2023-03-22 14:54:38.522 ERROR i.g.d.s.t.s.ControlRsp - Unable to initialize/start streaming for RSP device  [836MB/2GB 31%]
io.github.dsheirer.source.tuner.sdrplay.api.SDRPlayException: Device has already been initialized with listeners
	at io.github.dsheirer.source.tuner.sdrplay.api.device.Device.initStreamA(Device.java:196)
	at io.github.dsheirer.source.tuner.sdrplay.ControlRsp.startStream(ControlRsp.java:115)
	at io.github.dsheirer.source.tuner.sdrplay.RspTunerController.addBufferListener(RspTunerController.java:184)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager.startChannelSource(PolyphaseChannelManager.java:243)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$ChannelSourceEventListener.receive(PolyphaseChannelManager.java:433)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelManager$ChannelSourceEventListener.receive(PolyphaseChannelManager.java:423)
	at io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastProducerSourceEvent(TunerChannelSource.java:187)
	at io.github.dsheirer.source.tuner.channel.TunerChannelSource.start(TunerChannelSource.java:102)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.start(PolyphaseChannelSource.java:109)
	at io.github.dsheirer.module.ProcessingChain.start(ProcessingChain.java:726)
	at io.github.dsheirer.controller.channel.ChannelProcessingManager.startProcessing(ChannelProcessingManager.java:516)
	at io.github.dsheirer.controller.channel.ChannelProcessingManager.startChannelRequest(ChannelProcessingManager.java:318)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:109)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processPhase1ChannelGrant(P25TrafficChannelManager.java:374)
	at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processChannelGrant(P25TrafficChannelManager.java:253)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processChannelGrant(P25P1DecoderState.java:333)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBKGroupVoiceChannelGrantUpdate(P25P1DecoderState.java:1726)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBK(P25P1DecoderState.java:1113)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:308)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:153)
	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:124)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:48)
	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:97)
	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:90)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:92)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:34)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.dispatchMessage(P25P1MessageFramer.java:325)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:204)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:70)
	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:124)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:48)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:61)
	at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:117)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:93)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:116)
	at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:39)
	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:124)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:48)
	at io.github.dsheirer.source.tuner.channel.StreamProcessorWithHeartbeat.receive(StreamProcessorWithHeartbeat.java:112)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:145)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:41)
	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:109)
	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:50)
	at io.github.dsheirer.util.Dispatcher$Processor.run(Dispatcher.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by DSheirer** [comment]
@jamren01 are you still seeing this issue with the latest release?  If not, I'd like to close this as either resolved or OBE.
