### ISSUE TITLE
Unable to open UI elements (Add Stream combobox, Preferences UI, Playlist Editor UI)

### ISSUE THREAD

**Issue by louisik1** [DSheirer/sdrtrunk#1525]
Note: The bug is no-repro after restarting sdrtrunk.

ver 0.5.0

I went to add another Broadcastify Feed but nothing was happening when I clicked Add.  The Playlist Editor has been open for days, and I successfully added two feeds a few days ago.

**To Reproduce**
1. Playlist Editor was already open, hadn't been touched for a day or two
2. Streaming, Add
3. No response, no visual cue of the button being clicked
4. I closed the Playlist Editor
5. Playlist Editor and Preferences windows could not be opened from main menu or tab.
6. Output from console:

B a s e W n d : : C r e a t e ( G l a s s W n d C l a s s - G l a s s W i n d o w C l a s s - 3 0 )   e r r o r :   1 1 5 8
 Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: could not create platform window
        at javafx.graphics/com.sun.glass.ui.Window.<init>(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinWindow.<init>(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.createWindow(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.WindowStage.initPlatformWindow(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.WindowStage.init(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.createTKPopupStage(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.doVisibleChanging(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow$1.doVisibleChanging(Unknown Source)
        at javafx.graphics/com.sun.javafx.stage.PopupWindowHelper.visibleChangingImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.stage.WindowHelper.visibleChanging(Unknown Source)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
        at javafx.graphics/javafx.stage.Window.setShowing(Unknown Source)
        at javafx.graphics/javafx.stage.Window.show(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.showImpl(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.show(Unknown Source)
        at javafx.controls/javafx.scene.control.ContextMenu.doShow(Unknown Source)
        at javafx.controls/javafx.scene.control.ContextMenu.show(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.show(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$4(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
        at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
        at javafx.controls/javafx.scene.control.MenuButton.setShowing(Unknown Source)
        at javafx.controls/javafx.scene.control.MenuButton.show(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.behavior.MenuButtonBehaviorBase.mousePressed(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$0(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.removeListener(Unknown Source)
        at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.removeListener(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.unbindOwnerFocusedProperty(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.doVisibleChanged(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow$1.doVisibleChanged(Unknown Source)
        at javafx.graphics/com.sun.javafx.stage.PopupWindowHelper.visibleChangedImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.stage.WindowHelper.visibleChanged(Unknown Source)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
        at javafx.graphics/javafx.stage.Window.setShowing(Unknown Source)
        at javafx.graphics/javafx.stage.Window.hide(Unknown Source)
        at javafx.graphics/javafx.stage.PopupWindow.hide(Unknown Source)
        at javafx.controls/javafx.scene.control.ContextMenu.hide(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.hide(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$4(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
        at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
        at javafx.controls/javafx.scene.control.MenuButton.setShowing(Unknown Source)
        at javafx.controls/javafx.scene.control.MenuButton.hide(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.behavior.MenuButtonBehaviorBase.mousePressed(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$0(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
(this entire stack/error was shown multiple times in console)

The Preferences window would not open either.  I restarted sdrtrunk and it seems to be back to normal now.

System (Win 10, 3x nooelec nesdr smart) has been running fine for a couple weeks.  0.5.1 and 0.5.2 both had issues so I went down to 0.5.0 (freezing tuners pane requiring restart, or missing waterfall)

**Additional context**
Several days ago I installed VS Code and java components intending to dig in to the sdrtrunk code, but I haven't actually 'started' anything, I don't know yet whether I have everything I need, I just got busy and left it alone.  I believe I have added two Broadcastify feeds since installing the Code and other stuff, but I can't remember for sure.  Including screenshot of installed extensions.

![image](https://user-images.githubusercontent.com/491335/232253169-032d5c43-491f-4215-a2b4-0819873bdbee.png)

**Comment by DSheirer** [comment]
@louisik1 Not sure what caused this issue and without being able to reproduce, I don't think I can resolve.

I'm going to close the issue for now.  We can reopen this issue if you encounter the same behavior again.

cheers,
Denny
