### ISSUE TITLE
Radio Reference not connecting

### ISSUE THREAD

**Issue by givingdata** [DSheirer/sdrtrunk#1862]
**sdrtrunk Version**
master-branch

**Describe the bug**
I'm unable to import data from RadioReference.com. I have a Premium Subscription. I am able to connect to my account via the settings in SDR Trunk, and I have verified the connection. However, I get a warning dialogue after going back to the Playlist window (screenshot attached).

**To Reproduce**
1. Go to 'Playlist'
2. See Error: Warning dialogue appears (see screenshot)

**Expected behavior**
I should be able to import Radio Reference data

**Screenshots**
<img width="1068" alt="Screenshot 2024-02-23 at 8 37 48 AM" src="https://github.com/DSheirer/sdrtrunk/assets/43386512/9bea7bd0-1254-437a-881f-3f67d4aa127e">

**Application Log**
20240223 084613.026 [sdrtrunk cached thread 3] ERROR i.g.d.r.RadioReferenceService - Error parsing response: ��\]w���+Z~�Jb�ݺ�
20240223 084613.027 [sdrtrunk cached thread 3] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country list from radio reference  [81MB/105MB 77%]
io.github.dsheirer.rrapi.RadioReferenceException: Error deserializing XML response: ��\]w���+Z~�Jb�ݺ�
	at io.github.dsheirer.rrapi.RadioReferenceService.submitSync(RadioReferenceService.java:1232)
	at io.github.dsheirer.rrapi.RadioReferenceService.getCountries(RadioReferenceService.java:216)
	at io.github.dsheirer.gui.playlist.radioreference.RadioReferenceEditor.lambda$refreshCountries$4(RadioReferenceEditor.java:145)
	at io.github.dsheirer.rrapi.RadioReferenceService.deserialize(RadioReferenceService.java:1251)
	at io.github.dsheirer.rrapi.RadioReferenceService.submitSync(RadioReferenceService.java:1217)

**Desktop (optional - complete the following information):**
 - CPU Cores: [e.g. 4 cores]
 - RAM:[e.g. 16GB]

**Comment by bradjtrammell** [comment]
What OS is this running on?
What version of SDR Trunk are you running?

This information is missing from your report.

**Comment by givingdata** [comment]
Apologies—I thought I had included.

OS Version = Mac OS 14.3.1
SDR Trunk Version = Version 0.6.0 (final)

**Comment by DSheirer** [comment]
@givingdata Are you still seeing this same issue with the latest nightly release or with 0.6.1 beta 2 release?
