### ISSUE TITLE
0.6.0 Final error message

### ISSUE THREAD

**Issue by dleiken** [DSheirer/sdrtrunk#1882]
After a few hours of running SDRT I get the following error message. The program keeps running and does not crash. Let me know if you have any questions or need more info. 

**sdrtrunk Version**
0.6.0 Final

**Desktop **
-  Windows 11
 - CPU Cores: i7
 - RAM:16GB
 -

20240308 135220.810 [sdrtrunk polyphase channel thread 1] ERROR i.g.d.sample.Broadcaster - Error while broadcasting [class io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage] to listeners [Log Suppress 1/5]  [839MB/924MB 90%]

java.lang.IndexOutOfBoundsException: fromIndex: 168 > toIndex: 144

	at java.base/java.util.BitSet.checkRange(Unknown Source)

	at java.base/java.util.BitSet.get(Unknown Source)

	at io.github.dsheirer.bits.BinaryMessage.get(BinaryMessage.java:317)

	at io.github.dsheirer.bits.CorrectedBinaryMessage.getSubMessage(CorrectedBinaryMessage.java:93)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getAlias(L3HarrisTalkerAlias.java:82)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getIdentifiers(L3HarrisTalkerAlias.java:113)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage.getIdentifiers(MacMessage.java:131)

	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:58)

	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:43)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:115)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:108)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:104)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:42)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcast(P25P2SuperFrameDetector.java:231)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcastFragment(P25P2SuperFrameDetector.java:190)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.checkFragmentSync(P25P2SuperFrameDetector.java:255)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.receive(P25P2SuperFrameDetector.java:153)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:173)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:57)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:87)

	at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:146)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:121)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:142)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:48)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:143)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:40)

	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:112)

	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:57)

	at io.github.dsheirer.util.Dispatcher.process(Dispatcher.java:171)

	at io.github.dsheirer.util.Dispatcher$ProcessorWithHeartbeat.run(Dispatcher.java:213)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

20240308 135220.817 [sdrtrunk polyphase channel thread 1] ERROR i.g.d.sample.Broadcaster - Error while broadcasting [class io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage] to listeners [Log Suppress 2/5]  [839MB/924MB 90%]

java.lang.IndexOutOfBoundsException: fromIndex: 168 > toIndex: 144

	at java.base/java.util.BitSet.checkRange(Unknown Source)

	at java.base/java.util.BitSet.get(Unknown Source)

	at io.github.dsheirer.bits.BinaryMessage.get(BinaryMessage.java:317)

	at io.github.dsheirer.bits.CorrectedBinaryMessage.getSubMessage(CorrectedBinaryMessage.java:93)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getAlias(L3HarrisTalkerAlias.java:82)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.processMacMessage(P25P2DecoderState.java:406)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.receive(P25P2DecoderState.java:180)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.receive(P25P2DecoderState.java:105)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:115)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:108)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:104)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:42)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcast(P25P2SuperFrameDetector.java:231)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcastFragment(P25P2SuperFrameDetector.java:190)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.checkFragmentSync(P25P2SuperFrameDetector.java:255)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.receive(P25P2SuperFrameDetector.java:153)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:173)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:57)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:87)

	at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:146)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:121)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:142)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:48)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:143)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:40)

	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:112)

	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:57)

	at io.github.dsheirer.util.Dispatcher.process(Dispatcher.java:171)

	at io.github.dsheirer.util.Dispatcher$ProcessorWithHeartbeat.run(Dispatcher.java:213)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

20240308 135228.631 [sdrtrunk polyphase channel thread 1] ERROR i.g.d.sample.Broadcaster - Error while broadcasting [class io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage] to listeners [Log Suppress 1/5]  [457MB/924MB 49%]

java.lang.IndexOutOfBoundsException: fromIndex: 168 > toIndex: 144

	at java.base/java.util.BitSet.checkRange(Unknown Source)

	at java.base/java.util.BitSet.get(Unknown Source)

	at io.github.dsheirer.bits.BinaryMessage.get(BinaryMessage.java:317)

	at io.github.dsheirer.bits.CorrectedBinaryMessage.getSubMessage(CorrectedBinaryMessage.java:93)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getAlias(L3HarrisTalkerAlias.java:82)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getIdentifiers(L3HarrisTalkerAlias.java:113)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage.getIdentifiers(MacMessage.java:131)

	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:58)

	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:43)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:115)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:108)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:104)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:42)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcast(P25P2SuperFrameDetector.java:231)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcastFragment(P25P2SuperFrameDetector.java:190)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.checkFragmentSync(P25P2SuperFrameDetector.java:255)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.receive(P25P2SuperFrameDetector.java:153)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:173)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:57)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:87)

	at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:146)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:121)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:142)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:48)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:143)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:40)

	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:112)

	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:57)

	at io.github.dsheirer.util.Dispatcher.process(Dispatcher.java:171)

	at io.github.dsheirer.util.Dispatcher$ProcessorWithHeartbeat.run(Dispatcher.java:213)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

20240308 135228.633 [sdrtrunk polyphase channel thread 1] ERROR i.g.d.sample.Broadcaster - Error while broadcasting [class io.github.dsheirer.module.decode.p25.phase2.message.mac.MacMessage] to listeners [Log Suppress 2/5]  [476MB/924MB 51%]

java.lang.IndexOutOfBoundsException: fromIndex: 168 > toIndex: 144

	at java.base/java.util.BitSet.checkRange(Unknown Source)

	at java.base/java.util.BitSet.get(Unknown Source)

	at io.github.dsheirer.bits.BinaryMessage.get(BinaryMessage.java:317)

	at io.github.dsheirer.bits.CorrectedBinaryMessage.getSubMessage(CorrectedBinaryMessage.java:93)

	at io.github.dsheirer.module.decode.p25.phase2.message.mac.structure.l3harris.L3HarrisTalkerAlias.getAlias(L3HarrisTalkerAlias.java:82)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.processMacMessage(P25P2DecoderState.java:406)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.receive(P25P2DecoderState.java:180)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderState.receive(P25P2DecoderState.java:105)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:115)

	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:108)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:104)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageProcessor.receive(P25P2MessageProcessor.java:42)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcast(P25P2SuperFrameDetector.java:231)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.broadcastFragment(P25P2SuperFrameDetector.java:190)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.checkFragmentSync(P25P2SuperFrameDetector.java:255)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2SuperFrameDetector.receive(P25P2SuperFrameDetector.java:153)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:173)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2MessageFramer.receive(P25P2MessageFramer.java:57)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:87)

	at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:146)

	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:121)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:142)

	at io.github.dsheirer.module.decode.p25.phase2.P25P2DecoderHDQPSK.receive(P25P2DecoderHDQPSK.java:48)

	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)

	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:143)

	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:40)

	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:112)

	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:57)

	at io.github.dsheirer.util.Dispatcher.process(Dispatcher.java:171)

	at io.github.dsheirer.util.Dispatcher$ProcessorWithHeartbeat.run(Dispatcher.java:213)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DSheirer** [comment]
Duplicate.

Resolved here: https://github.com/DSheirer/sdrtrunk/issues/1783
