### ISSUE TITLE
P25P1 Error Message On Control Channel Rotation

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1998]
**sdrtrunk Version**
master

**Describe the bug**
Result of changes from #1996 

```
20241001 111944.244 [sdrtrunk channel [0/P25-1] 151287500 thread 1]
INFO  i.g.d.a.c.mbe.AmbeAudioModule - AMBE CODEC successfully loaded -
P25-2/DMR/NXDN audio will be available  [63MB/260MB 24%]
20241001 113108.195 [sdrtrunk scheduled thread 2] ERROR
i.g.d.sample.Broadcaster - Error while broadcasting [class
io.github.dsheirer.channel.state.DecoderStateEvent] to listeners [Log
Suppress 1/5]  [96MB/260MB 37%]
java.util.ConcurrentModificationException: null
    at java.base/java.util.HashMap.forEach(Unknown Source)
    at
io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processControlFrequencyUpdate(P25TrafficChannelManager.java:174)
    at
io.github.dsheirer.module.decode.traffic.TrafficChannelManager.setCurrentControlFrequency(TrafficChannelManager.java:57)
    at
io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receiveDecoderStateEvent(P25P1DecoderState.java:2207)
    at
io.github.dsheirer.channel.state.AbstractDecoderState$DecoderStateEventListener.receive(AbstractDecoderState.java:177)
    at
io.github.dsheirer.channel.state.AbstractDecoderState$DecoderStateEventListener.receive(AbstractDecoderState.java:172)
    at
io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
    at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
    at
io.github.dsheirer.channel.state.SingleChannelState.broadcast(SingleChannelState.java:357)
    at
io.github.dsheirer.channel.state.SingleChannelState$SourceEventListener.receive(SingleChannelState.java:380)
    at
io.github.dsheirer.channel.state.SingleChannelState$SourceEventListener.receive(SingleChannelState.java:370)
    at
io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
    at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
    at
io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastConsumerSourceEvent(TunerChannelSource.java:205)
    at
io.github.dsheirer.source.tuner.channel.MultiFrequencyTunerChannelSource$ConsumerSourceEventAdapter.receive(MultiFrequencyTunerChannelSource.java:327)
    at
io.github.dsheirer.source.tuner.channel.MultiFrequencyTunerChannelSource$ConsumerSourceEventAdapter.receive(MultiFrequencyTunerChannelSource.java:322)
    at
io.github.dsheirer.source.tuner.channel.TunerChannelSource.broadcastConsumerSourceEvent(TunerChannelSource.java:205)
    at
io.github.dsheirer.source.tuner.channel.TunerChannelSource.start(TunerChannelSource.java:105)
    at
io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.start(PolyphaseChannelSource.java:109)
    at
io.github.dsheirer.source.tuner.channel.MultiFrequencyTunerChannelSource.getNextSource(MultiFrequencyTunerChannelSource.java:125)
    at
io.github.dsheirer.source.tuner.channel.MultiFrequencyTunerChannelSource.rotate(MultiFrequencyTunerChannelSource.java:102)
    at
io.github.dsheirer.source.tuner.channel.MultiFrequencyTunerChannelSource.process(MultiFrequencyTunerChannelSource.java:309)
    at
io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:51)
    at
io.github.dsheirer.source.SourceEventListenerToProcessorAdapter.receive(SourceEventListenerToProcessorAdapter.java:25)
    at
io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
    at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
    at
io.github.dsheirer.source.tuner.channel.rotation.ChannelRotationMonitor.checkState(ChannelRotationMonitor.java:148)
    at
io.github.dsheirer.source.tuner.channel.rotation.ChannelRotationMonitor.lambda$start$0(ChannelRotationMonitor.java:179)
    at
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown
Source)
    at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown
Source)
    at
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown
Source)
    at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by DSheirer** [comment]
Resolved with commit.
