### ISSUE TITLE
Version 0.6.1 Beta 2

### ISSUE THREAD

**Issue by OhioRSN** [DSheirer/sdrtrunk#2025]
Not sure what this issue is but it briefly made all my channels go dead then come back, just figured I would share.
 
ProxMox with Windows 11 VM
12 Tuners on PCI Card With 2 USB Hubs
6 Trunking Systems
12 CPU
48GB RAM

2024-10-17 08:31:11.799 ERROR i.g.d.sample.Broadcaster - Error while broadcasting [class io.github.dsheirer.module.decode.p25.phase1.message.ldu.LDU1Message] to listeners [Log Suppress 1/5]  [628MB/1GB 31%]
java.lang.NullPointerException: Cannot invoke "jmbe.iface.IAudioCodec.getAudio(byte[])" because the return value of "io.github.dsheirer.module.decode.p25.audio.P25P1AudioModule.getAudioCodec()" is null
        at io.github.dsheirer.module.decode.p25.audio.P25P1AudioModule.processAudio(P25P1AudioModule.java:140)
        at io.github.dsheirer.module.decode.p25.audio.P25P1AudioModule.receive(P25P1AudioModule.java:88)
        at io.github.dsheirer.module.decode.p25.audio.P25P1AudioModule.receive(P25P1AudioModule.java:36)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:115)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:108)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.dispatch(P25P1MessageProcessor.java:250)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:141)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:49)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.dispatchMessage(P25P1MessageFramer.java:349)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:203)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:69)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:87)
        at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:146)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:121)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:130)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:39)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:128)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:52)
        at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:145)
        at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.receive(PolyphaseChannelSource.java:40)
        at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:113)
        at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.lambda$new$0(ChannelOutputProcessor.java:56)
        at io.github.dsheirer.util.Dispatcher.process(Dispatcher.java:184)
        at io.github.dsheirer.util.Dispatcher$ProcessorWithHeartbeat.run(Dispatcher.java:226)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Dannyblack555** [comment]
man i HATE github .. WHY is everything so difficult ?? wheres the program file, exe or whatever ? ?? i downloaded the zip, but no executable there ..
