### ISSUE TITLE
SHOUTcast 2.0 Error

### ISSUE THREAD

**Issue by mncigarman** [DSheirer/sdrtrunk#289]
I am trying to connect to my Shoutast channel and get an error when I hit save.  Here is the relevant portion of the log:

20171121 170038.053 [NioProcessor-33] INFO  a.broadcast.AudioBroadcaster - [Hubbard County MN ARMER] status: Error  [466MB/563MB 82%]
20171121 170630.818 [sdrtrunk pool-1-thread-1] INFO  a.broadcast.AudioBroadcaster - [Hubbard County MN ARMER] status: Connecting  [322MB/722MB 44%]
20171121 170632.890 [NioProcessor-39] ERROR a.b.s.v.ShoutcastV2AudioBroadcaster - Broadcast error  [538MB/722MB 74%]
java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:180) ~[commons-lang3-3.2.1.jar:3.2.1]
	at util.XTEA.encrypt(Unknown Source) ~[sdrtrunk.jar:na]
	at audio.broadcast.shoutcast.v2.ultravox.AuthenticateBroadcast.encrypt(Unknown Source) ~[sdrtrunk.jar:na]
	at audio.broadcast.shoutcast.v2.ultravox.AuthenticateBroadcast.setCredentials(Unknown Source) ~[sdrtrunk.jar:na]
	at audio.broadcast.shoutcast.v2.ShoutcastV2AudioBroadcaster$ShoutcastV2IOHandler.messageReceived(Unknown Source) ~[sdrtrunk.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:858) ~[mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:947) [mina-core-2.0.16.jar:na]
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:398) [mina-core-2.0.16.jar:na]
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:234) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:947) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:703) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:659) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:648) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:68) [mina-core-2.0.16.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1120) [mina-core-2.0.16.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.16.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:na]
	at java.base/java.lang.Thread.run(Unknown Source) [na:na]

**Comment by DSheirer** [comment]
Is the username or password blank or empty?

**Comment by conradkelly** [comment]
No, they are both filled in.

**Comment by DSheirer** [comment]
@mncigarman I pushed a new beta release of version 0.3.2 that contains a patch for the shoutcast 2 error you were seeing.  If you get a chance, please test this new release and let me know if this works, or not?

Thanks, 
Denny

**Comment by conradkelly** [comment]
Great, thanks! I will give it a try when I get home tomorrow.
