### ISSUE TITLE
java exception

### ISSUE THREAD

**Issue by gametimebrizzle** [DSheirer/sdrtrunk#337]
I am getting the error below when attempting to run sdrtrunk, this happened randomly today - as I have been using this awesome program for a little while now...I'm not sure how to debug this.

How to reproduce:
using cmd/PS:
run_sdrtrunk_windows.bat

What I've tried:
- Reboot
- Remove / reinstall sdrtrunk + reboot
- Remove / reinstall JDK + reboot
- Remove / re{install|compile} JMBE + reboot

What I haven't tried:
- Reinstall ant
- altering PATH (I have checked the path, but see no reason to change anything)

Here is the exception thrown (followed by the full console output)

```
Exception in thread "main" java.lang.IllegalArgumentException: Mixer not supported: null
        at javax.sound.sampled.AudioSystem.getMixer(Unknown Source)
        at io.github.dsheirer.audio.AudioManager.loadSettings(AudioManager.java:97)
        at io.github.dsheirer.audio.AudioManager.<init>(AudioManager.java:85)
        at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:143)
        at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:200)
```
> PS S:\Downloads> java -jar sdr-trunk-all-0.3.3-beta.3.jar
> 14:14:20.351 INFO  i.g.dsheirer.gui.SDRTrunk - *******************************************************************  [11MB/123MB 9%]
> 14:14:20.382 INFO  i.g.dsheirer.gui.SDRTrunk - **** sdrtrunk: a trunked radio and digital decoding application ***  [11MB/123MB 9%]
> 14:14:20.382 INFO  i.g.dsheirer.gui.SDRTrunk - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [11MB/123MB 9%]
> 14:14:20.382 INFO  i.g.dsheirer.gui.SDRTrunk - *******************************************************************  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Memory Logging Format: [Used/Allocated PercentUsed%]  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Host CPU Cores:        4  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Name:          Windows 10  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Arch:          amd64  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Version:       10.0  [11MB/123MB 9%]
> 14:14:20.397 INFO  i.g.dsheirer.gui.SDRTrunk - Host Max Java Memory:  1 GB  [11MB/123MB 9%]
> 14:14:20.413 INFO  i.g.d.util.ThreadPool - Application thread pool created with [4] threads  [11MB/123MB 9%]
> 14:14:20.413 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: C:\Users\user1\SDRTrunk  [11MB/123MB 9%]
> 14:14:20.429 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [C:\Users\user1\SDRTrunk\SDRTrunk.properties]  [11MB/123MB 9%]
> 14:14:20.444 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [C:\Users\user1\SDRTrunk\SDRTrunk.properties]  [11MB/123MB 9%]
> 14:14:20.460 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [C:\Users\user1\SDRTrunk\settings\settings.xml]  [11MB/123MB 9%]
> 14:14:21.069 INFO  i.g.d.s.m.MixerManager - loading system mixer devices
>   [31MB/123MB 25%]
> 14:14:21.069 INFO  i.g.d.s.r.RecordingSourceManager - RecordingSourceManager - discovered [0] recording configurations  [31MB/123MB 25%]
> 14:14:24.797 INFO  i.g.d.s.t.TunerManager - LibUSB API Version: 16777474  [11MB/123MB 9%]
> 14:14:24.797 INFO  i.g.d.s.t.TunerManager - LibUSB Version: 1.0.18.10866  [11MB/123MB 9%]
> 14:14:24.891 INFO  i.g.d.s.t.TunerManager - discovered [17] attached USB devices  [11MB/123MB 9%]
> 14:14:24.891 INFO  i.g.d.s.t.TunerManager - usb device [8086:293C] NOT LOADED: Unknown Device  [11MB/123MB 9%]
> --- snip ---
> 14:14:26.485 INFO  i.g.d.s.t.TunerManager - usb device [0BDA:2838] LOADED: RTL2832 SDR/R820T 00000001  [11MB/123MB 9%]
> 14:14:26.485 INFO  i.g.d.s.t.TunerManager - usb device [413C:8130] NOT LOADED: Unknown Device  [11MB/123MB 9%]
> Exception in thread "main" java.lang.IllegalArgumentException: Mixer not supported: null
>         at javax.sound.sampled.AudioSystem.getMixer(Unknown Source)
>         at io.github.dsheirer.audio.AudioManager.loadSettings(AudioManager.java:97)
>         at io.github.dsheirer.audio.AudioManager.<init>(AudioManager.java:85)
>         at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:143)
>         at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:200)

**Comment by gametimebrizzle** [comment]
I do have an audio mixer at the ready...

**Comment by gametimebrizzle** [comment]
ISSUE RESOLVED: Reason - my bluetooth speaker lost its paired state - after I removed the speaker from bluetooth devices and reestablished a connection everything works just fine.

Feel free to just completely delete this issue as it is a duplicate and I don't add much helpful information if anyone else experiences this.
