### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel

### ISSUE THREAD

**Issue by magic7s** [DSheirer/sdrtrunk#386]
Fails to launch with `java -jar sdr-trunk-all-0.4.0-alpha.2.jar`
Fails to launch with `java -jar sdr-trunk-all-0.3.4-beta.2.jar`
Both versions launch when setting `-Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel`
Working: `java -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar sdr-trunk-all-0.4.0-alpha.2.jar`

`MacOS 10.13.6
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)`

Full error
`
BRADDOWN-M-H410:SDRTrunk braddown$ java -jar sdr-trunk-all-0.4.0-alpha.2.jar
10:31:39.022 INFO  i.g.dsheirer.gui.SDRTrunk - *******************************************************************  [17MB/128MB 13%]
10:31:39.046 INFO  i.g.dsheirer.gui.SDRTrunk - **** sdrtrunk: a trunked radio and digital decoding application ***  [17MB/128MB 13%]
10:31:39.046 INFO  i.g.dsheirer.gui.SDRTrunk - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [17MB/128MB 13%]
10:31:39.047 INFO  i.g.dsheirer.gui.SDRTrunk - *******************************************************************  [17MB/128MB 13%]
10:31:39.047 INFO  i.g.dsheirer.gui.SDRTrunk - Memory Logging Format: [Used/Allocated PercentUsed%]  [17MB/128MB 13%]
10:31:39.048 INFO  i.g.dsheirer.gui.SDRTrunk - Host CPU Cores:        4  [17MB/128MB 13%]
10:31:39.048 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Name:          Mac OS X  [17MB/128MB 13%]
10:31:39.049 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Arch:          x86_64  [17MB/128MB 13%]
10:31:39.049 INFO  i.g.dsheirer.gui.SDRTrunk - Host OS Version:       10.13.6  [17MB/128MB 13%]
10:31:39.050 INFO  i.g.dsheirer.gui.SDRTrunk - Host Max Java Memory:  2 GB  [17MB/128MB 13%]
10:31:39.076 INFO  i.g.d.util.ThreadPool - Application thread pool created with [4] threads  [17MB/128MB 13%]
10:31:39.078 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /Users/braddown/SDRTrunk  [17MB/128MB 13%]
10:31:39.088 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/Users/braddown/SDRTrunk/SDRTrunk.properties]  [17MB/128MB 13%]
10:31:39.088 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/Users/braddown/SDRTrunk/SDRTrunk.properties]  [17MB/128MB 13%]
10:31:39.183 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [/Users/braddown/SDRTrunk/settings/settings.xml]  [5MB/128MB 4%]
10:31:41.005 INFO  i.g.d.s.m.MixerManager - loading system mixer devices
	[LOADED]     Input:  Default Audio Device CHANNELS: [LEFT, RIGHT, MONO]
	[LOADED]     Output: Default Audio Device CHANNELS: [MONO, STEREO]
	[LOADED]     Input:  Built-in Microphone CHANNELS: [LEFT, RIGHT, MONO]
	[LOADED]     Output: Built-in Output CHANNELS: [MONO, STEREO]
	[LOADED]     Input:  Soundflower (2ch) CHANNELS: [LEFT, RIGHT, MONO]
	[LOADED]     Output: Soundflower (2ch) CHANNELS: [MONO, STEREO]
	[LOADED]     Input:  Soundflower (64ch) CHANNELS: [LEFT, RIGHT, MONO]
	[LOADED]     Output: Soundflower (64ch) CHANNELS: [MONO, STEREO]
  [11MB/128MB 9%]
10:31:41.006 INFO  i.g.d.s.r.RecordingSourceManager - RecordingSourceManager - discovered [0] recording configurations  [11MB/128MB 9%]
10:31:41.156 INFO  i.g.d.s.t.TunerManager - LibUSB API Version: 16777474  [12MB/128MB 10%]
10:31:41.157 INFO  i.g.d.s.t.TunerManager - LibUSB Version: 1.0.18.10866  [12MB/128MB 10%]
10:31:41.157 INFO  i.g.d.s.t.TunerManager - discovered [5] attached USB devices  [12MB/128MB 10%]
10:31:42.806 INFO  i.g.d.s.t.TunerManager - usb device [0BDA:2838] LOADED: RTL2832 SDR/R820T 00000001  [14MB/128MB 11%]
10:31:44.404 INFO  i.g.d.s.t.TunerManager - usb device [0BDA:2838] LOADED: RTL2832 SDR/R820T 00000001  [14MB/128MB 11%]
10:31:44.408 INFO  i.g.d.s.t.TunerManager - usb device [05AC:828F] NOT LOADED: Unknown Device  [14MB/128MB 11%]
10:31:44.409 INFO  i.g.d.s.t.TunerManager - usb device [0A5C:4500] NOT LOADED: Unknown Device  [14MB/128MB 11%]
10:31:44.410 INFO  i.g.d.s.t.TunerManager - usb device [05AC:8007] NOT LOADED: Unknown Device  [14MB/128MB 11%]
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:845)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
	at com.jidesoft.swing.JideSplitButton.updateUI(JideSplitButton.java:109)
	at java.desktop/javax.swing.JMenuItem.init(JMenuItem.java:208)
	at java.desktop/javax.swing.JMenuItem.<init>(JMenuItem.java:147)
	at java.desktop/javax.swing.JMenuItem.<init>(JMenuItem.java:124)
	at java.desktop/javax.swing.JMenu.<init>(JMenu.java:161)
	at com.jidesoft.swing.JideMenu.<init>(JideMenu.java:64)
	at com.jidesoft.swing.JideSplitButton.<init>(JideSplitButton.java:49)
	at io.github.dsheirer.module.decode.event.MessageActivityPanel$MessageHistoryButton.<init>(MessageActivityPanel.java:183)
	at io.github.dsheirer.module.decode.event.MessageActivityPanel$MessageManagementPanel.<init>(MessageActivityPanel.java:151)
	at io.github.dsheirer.module.decode.event.MessageActivityPanel.<init>(MessageActivityPanel.java:52)
	at io.github.dsheirer.channel.metadata.ChannelMetadataViewer.<init>(ChannelMetadataViewer.java:51)
	at io.github.dsheirer.controller.ControllerPanel.<init>(ControllerPanel.java:79)
	at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:175)
	at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:585)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 17 more
`

**Comment by DSheirer** [comment]
Resolved.
