### ISSUE TITLE
P25 Decoder - ClassCastException for TelephoneInterconnect voice channel grant

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#399]
20180901 233210.955 [sdrtrunk pool-1-thread-1] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [
634MB/955MB 66%]
java.lang.ClassCastException: io.github.dsheirer.module.decode.p25.message.tsbk.TSBKMessage cannot be cast to io.github.dsheirer.module.decode.
p25.message.tsbk.osp.voice.TelephoneInterconnectVoiceChannelGrantUpdate
        at io.github.dsheirer.module.decode.p25.P25DecoderState.processTSBKChannelGrant(P25DecoderState.java:3171)
        at io.github.dsheirer.module.decode.p25.P25DecoderState.processTSBK(P25DecoderState.java:1551)
        at io.github.dsheirer.module.decode.p25.P25DecoderState.receive(P25DecoderState.java:364)
        at io.github.dsheirer.module.decode.p25.P25DecoderState.receive(P25DecoderState.java:146)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:121)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:39)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:102)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:95)
        at io.github.dsheirer.module.decode.p25.P25MessageProcessor.receive(P25MessageProcessor.java:76)
        at io.github.dsheirer.module.decode.p25.P25MessageProcessor.receive(P25MessageProcessor.java:14)
        at io.github.dsheirer.module.decode.p25.P25MessageFramer.dispatch(P25MessageFramer.java:197)
        at io.github.dsheirer.module.decode.p25.P25MessageFramer.access$300(P25MessageFramer.java:41)
        at io.github.dsheirer.module.decode.p25.P25MessageFramer$P25MessageAssembler.checkComplete(P25MessageFramer.java:625)
These errors continue for awhile then the log just shows:

20180901 235942.522 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [646MB/1GB 60%]
java.lang.ClassCastException: null
20180901 235942.572 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [650MB/1GB 60%]
java.lang.ClassCastException: null
20180901 235942.622 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [652MB/1GB 61%]
java.lang.ClassCastException: null
20180901 235942.672 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [659MB/1GB 61%]
java.lang.ClassCastException: null
20180901 235942.722 [sdrtrunk pool-1-thread-1] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [660MB/1GB 61%]
java.lang.ClassCastException: null
20180901 235942.772 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [662MB/1GB 62%]
java.lang.ClassCastException: null
20180901 235942.825 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [669MB/1GB 62%]
java.lang.ClassCastException: null
20180901 235942.872 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [671MB/1GB 62%]
java.lang.ClassCastException: null
20180901 235942.922 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [675MB/1GB 63%]
java.lang.ClassCastException: null
20180901 235942.972 [sdrtrunk pool-1-thread-4] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [680MB/1GB 63%]
java.lang.ClassCastException: null
20180901 235943.022 [sdrtrunk pool-1-thread-1] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [684MB/1GB 64%]
java.lang.ClassCastException: null
20180901 235943.072 [sdrtrunk pool-1-thread-1] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [684MB/1GB 64%]
java.lang.ClassCastException: null
20180901 235943.124 [sdrtrunk pool-1-thread-1] ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [691MB/1GB 64%]
java.lang.ClassCastException: null

**Comment by DSheirer** [comment]
Issue: the TSBKMessageFactory is missing a switch statement for:

case TELEPHONE_INTERCONNECT_VOICE_CHANNEL_GRANT_UPDATE:
	return new TelephoneInterconnectVoiceChannelGrantUpdate(message, duid, aliasList);

**Comment by DSheirer** [comment]
Check for other missing switch statements ...
