### ISSUE TITLE
Add a recording to the tree -> class cast exception at load time

### ISSUE THREAD

**Issue by gbin** [DSheirer/sdrtrunk#46]
```
12:30:17.506 ERROR o.j.swingx.JXMapViewer - JXMapViewer could not load 'loading.png'
Exception in thread "main" java.lang.ClassCastException: source.config.SourceConfiguration cannot be cast to source.config.SourceConfigRecording
        at controller.channel.Channel.getTunerChannel(Unknown Source)
        at controller.channel.Channel.isWithin(Unknown Source)
        at spectrum.OverlayPanel.frequencyChanged(Unknown Source)
        at spectrum.SpectralDisplayPanel.frequencyChanged(Unknown Source)
        at spectrum.SpectralDisplayPanel.tunerSelected(Unknown Source)
        at controller.ConfigurationControllerModel.fireTunerSelectedEvent(Unknown Source)
        at controller.ConfigurationControllerModel.fireFirstTunerSelected(Unknown Source)
        at gui.SDRTrunk.initGUI(Unknown Source)
        at gui.SDRTrunk.<init>(Unknown Source)
        at gui.SDRTrunk.main(Unknown Source)
```

**Comment by DSheirer** [comment]
This feature hasn't been implemented yet.  Another user was attempting to add wideband recordings and then run decoders against it.  I added skeleton code to support recordings for the user to code out, but the feature was never completed.  I'll probably remove the recordings node until it gets finished.
