### ISSUE TITLE
Audio Recordings Failing

### ISSUE THREAD

**Issue by JoshGore** [DSheirer/sdrtrunk#543]
Assume this is related to #480 but I am still getting .tmp files instead of audio recordings in Version 0.4.0 Alpha 9 (Windows 10 x64), P25 System with audio decoding clearly. Following error in the console:

java.lang.IllegalStateException: User count is below zero.  This indicates that this buffer's decrement user count was invoked by more than the expected user count
        at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.recycle(AbstractReusableBuffer.java:119)
        at io.github.dsheirer.sample.buffer.AbstractReusableBuffer.decrementUserCount(AbstractReusableBuffer.java:100)
        at io.github.dsheirer.record.wave.AudioPacketWaveRecorder.write(AudioPacketWaveRecorder.java:225)
        at io.github.dsheirer.record.wave.AudioPacketWaveRecorder$BufferProcessor.run(AudioPacketWaveRecorder.java:245)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
23:20:15.882 ERROR i.g.d.r.RecorderManager - Error while processing audio buffers

**Comment by DSheirer** [comment]
Resolved with MR #675
