### ISSUE TITLE
Pipe Error when selecting the tuner

### ISSUE THREAD

**Issue by ryanthomp** [DSheirer/sdrtrunk#594]
When I am in the tuner screen and attempt to click on the tuner it throws an error and says 
```R820T Tuner Controller - couldn't apply the sample rate setting [2.400MHz] USB error 9: error writing byte buffer: Pipe error```

I am using JDK 8 231
and JRE 8u231

The read out from console is here:
```
12:54:38.176 ERROR i.g.d.s.t.r.r.R820TTunerEditor - R820T Tuner Controller - couldn't apply sample rate setting [2.400 MHz]  [49MB/256MB 19%]
org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error
```

**Comment by DSheirer** [comment]
This usually indicates that the tuner is in a bad state.  Try unplugging and replugging the dongle.  Or, try plugging the dongle into another USB port.

**Comment by ryanthomp** [comment]
That's what I assumed since it works on my laptop I even reinstalled LibUSB drivers and unplugged and switched ports, however, none of those worked I assume the issue is on my end possibly bugged drivers or something

**Comment by DSheirer** [comment]
Ryan ... is this issue resolved for you?  If so, I'd like to close the ticket.

**Comment by whelgeson** [comment]
@ryanthomp - I just encountered this issue in Windows 10. The solution that fixed it was to Change the driver type using USB Driver Tool, changing it to "USB Composite Device". All other drivers would cause this issue to show up.

**Comment by ryanthomp** [comment]
@DSheirer yes this is solved you can close this, just realized it was still open. The reason it wasn't working is because in zadig I replaced the Bulk In Interface (1) with the WinUSB driver.

**Comment by aaomidi** [comment]
@whelgeson what is the USB Driver Tool?

**Comment by DSheirer** [comment]
@aaomidi Zadig - reinstall the drivers.

**Comment by aaomidi** [comment]
@DSheirer I've installed on 2 separate OSes, I'm guessing there is something up with this USB device I've bought.

**Comment by DSheirer** [comment]
Another issue is that sometimes the USB port that you're using doesn't have enough power.  You can try using a different usb port on another bus.  Some folks have resorted to using an external (powered) usb hub.

Does the device work with other SDR applications?

**Comment by aaomidi** [comment]
Yeah it works with SDRSharp.

I'll try an external powered usb hub.

**Comment by nr0q** [comment]
I'm having the same error here using the latest release of SDRTrunk. Here's my full log output. 
I've tried every USB port that I have with and without a powered HUB. 

`[mchambers@nr0q-1 bin]$ ./sdr-trunk
13:47:20.628 INFO  i.g.d.icon.IconModel - loading icons file [/home/mchambers/SDRTrunk/settings/icons.xml]  [11MB/250MB 4%]
13:47:20.633 INFO  i.g.d.icon.IconModel - Icons file not found at [/home/mchambers/SDRTrunk/settings/icons.xml]  [11MB/250MB 4%]
13:47:21.127 INFO  i.g.d.log.ApplicationLog - Application Log File: /home/mchambers/SDRTrunk/logs/sdrtrunk_app.log  [19MB/250MB 7%]
13:47:21.143 INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.5.0-alpha6  [20MB/250MB 8%]
13:47:21.143 INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 6.3  [20MB/250MB 8%]
13:47:21.144 INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2020-10-26T04:29:57.816-0400  [20MB/250MB 8%]
13:47:21.144 INFO  i.g.d.log.ApplicationLog - Build-JDK         : 15 (BellSoft 15+36  [20MB/250MB 8%]
13:47:21.144 INFO  i.g.d.log.ApplicationLog - Build OS          : Linux (amd64 4.4.0-193-generic  [20MB/250MB 8%]
13:47:21.144 INFO  i.g.d.log.ApplicationLog -   [20MB/250MB 8%]
13:47:21.144 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - Host OS Name:          Linux  [20MB/250MB 8%]
13:47:21.145 INFO  i.g.d.log.ApplicationLog - Host OS Arch:          amd64  [20MB/250MB 8%]
13:47:21.146 INFO  i.g.d.log.ApplicationLog - Host OS Version:       5.9.13-200.fc33.x86_64  [20MB/250MB 8%]
13:47:21.146 INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        12  [20MB/250MB 8%]
13:47:21.146 INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  3 GB  [20MB/250MB 8%]
13:47:21.146 INFO  i.g.d.log.ApplicationLog - Storage Directories:  [20MB/250MB 8%]
13:47:21.146 INFO  i.g.d.log.ApplicationLog -  Application Root: /home/mchambers/SDRTrunk  [20MB/250MB 8%]
13:47:21.147 INFO  i.g.d.log.ApplicationLog -  Application Log:  /home/mchambers/SDRTrunk/logs  [20MB/250MB 8%]
13:47:21.147 INFO  i.g.d.log.ApplicationLog -  Event Log:        /home/mchambers/SDRTrunk/event_logs  [20MB/250MB 8%]
13:47:21.147 INFO  i.g.d.log.ApplicationLog -  Playlist:         /home/mchambers/SDRTrunk/playlist  [20MB/250MB 8%]
13:47:21.148 INFO  i.g.d.log.ApplicationLog -  Recordings:       /home/mchambers/SDRTrunk/recordings  [20MB/250MB 8%]
13:47:21.251 INFO  i.g.d.util.ThreadPool - Application thread pool created with [12] threads  [7MB/250MB 3%]
13:47:21.251 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /home/mchambers/SDRTrunk  [7MB/250MB 3%]
13:47:21.252 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/home/mchambers/SDRTrunk/SDRTrunk.properties]  [7MB/250MB 3%]
13:47:21.252 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/home/mchambers/SDRTrunk/SDRTrunk.properties]  [7MB/250MB 3%]
13:47:21.261 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [/home/mchambers/SDRTrunk/settings/settings.xml]  [8MB/250MB 3%]
13:47:21.455 INFO  i.g.d.s.r.RecordingSourceManager - RecordingSourceManager - discovered [0] recording configurations  [20MB/34MB 60%]
13:47:21.466 INFO  i.g.d.s.t.TunerManager - LibUSB API Version: 16777478  [21MB/34MB 63%]
13:47:21.467 INFO  i.g.d.s.t.TunerManager - LibUSB Version: 1.0.22.11312  [21MB/34MB 63%]
13:47:21.467 INFO  i.g.d.s.t.TunerManager - discovered [11] attached USB devices  [21MB/34MB 63%]
13:47:21.470 INFO  i.g.d.s.t.TunerManager - USB Bus [4] Device [1D6B:0003] Hub Device  [21MB/34MB 63%]
13:47:21.471 INFO  i.g.d.s.t.TunerManager - USB Bus [3] Device [08BB:2902] Unknown Device - Class 0  [21MB/34MB 63%]
13:47:21.471 INFO  i.g.d.s.t.TunerManager - USB Bus [3] Device [05E3:0510] Miscellaneous Device  [21MB/34MB 63%]
13:47:21.471 INFO  i.g.d.s.t.TunerManager - USB Bus [3] Device [1D6B:0002] Hub Device  [21MB/34MB 63%]
13:47:21.472 INFO  i.g.d.s.t.TunerManager - USB Bus [2] Device [1D6B:0003] Hub Device  [21MB/34MB 64%]
13:47:24.186 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [0BDA:2838] LOADED: RTL2832 SDR/R820T 00000001 Max Rate:38400000 bps  [23MB/34MB 70%]
13:47:24.187 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [1C4F:0032] Unknown Device - Class 0  [23MB/34MB 70%]
13:47:24.187 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [046D:C31C] Unknown Device - Class 0  [23MB/34MB 70%]
13:47:24.187 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [09AE:3016] Unknown Device - Class 0  [23MB/34MB 70%]
13:47:24.188 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [05E3:0608] Hub Device  [23MB/34MB 70%]
13:47:24.188 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Device [1D6B:0002] Hub Device  [23MB/34MB 70%]
13:47:24.188 INFO  i.g.d.s.t.TunerManager - -------------------------------------------------------------  [23MB/34MB 70%]
13:47:24.188 INFO  i.g.d.s.t.TunerManager - USB Bus - Potential Maximum Data Rates  [23MB/34MB 70%]
13:47:24.193 INFO  i.g.d.s.t.TunerManager - USB Bus [1] Rate [38400000] bits per second  [23MB/34MB 70%]
13:47:25.090 INFO  i.g.d.p.PlaylistManager - Loading playlist [/home/mchambers/SDRTrunk/playlist/default.xml]  [18MB/36MB 51%]
13:47:25.169 INFO  i.g.dsheirer.gui.SDRTrunk - starting main application gui  [22MB/36MB 62%]
13:47:25.708 INFO  i.g.d.s.t.u.USBMasterProcessor - Starting USB master processor thread  [24MB/40MB 61%]
13:47:28.568 INFO  i.g.d.c.c.ChannelAutoStartFrame - Channel auto-start canceled by user  [25MB/48MB 53%]

(java:2480569): Gtk-WARNING **: 13:47:32.783: Theme parsing error: gtk.css:2:33: Failed to import: Error opening file /home/mchambers/.config/gtk-3.0/window_decorations.css: No such file or directory
13:47:47.638 INFO  i.g.d.s.tuner.TunerModel - Unable to source channel [156187500] from preferred tuner [RTL2832 SDR/R820T 00000001] - searching for another tuner  [115MB/168MB 68%]
13:47:47.644 ERROR i.g.d.g.p.c.ChannelConfigurationEditor - Error starting channel [Macon] - No Tuner Available  [116MB/168MB 69%]
13:48:21.567 ERROR i.g.d.s.t.r.r.R820TTunerEditor - R820T Tuner Controller - couldn't apply sample rate setting [2.400 MHz]  [134MB/168MB 79%]
org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.write(RTL2832TunerController.java:825)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeDemodRegister(RTL2832TunerController.java:721)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.setSampleRate(RTL2832TunerController.java:975)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor$3.actionPerformed(R820TTunerEditor.java:144)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor.setItem(R820TTunerEditor.java:589)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor.setItem(R820TTunerEditor.java:55)
        at io.github.dsheirer.source.tuner.TunerEditor.setTunerConfiguration(TunerEditor.java:376)
        at io.github.dsheirer.source.tuner.TunerEditor$2.valueChanged(TunerEditor.java:151)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
        at java.desktop/javax.swing.JTable.setRowSelectionInterval(Unknown Source)
        at io.github.dsheirer.source.tuner.TunerEditor.setItem(TunerEditor.java:298)
        at io.github.dsheirer.source.tuner.TunerViewPanel$1.valueChanged(TunerViewPanel.java:107)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.write(RTL2832TunerController.java:825)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeDemodRegister(RTL2832TunerController.java:721)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.enableI2CRepeater(RTL2832TunerController.java:625)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeI2CRegister(RTL2832TunerController.java:684)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerController.writeR820TRegister(R820TTunerController.java:662)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerController.setLNAGain(R820TTunerController.java:706)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerController.setGain(R820TTunerController.java:692)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor$6.actionPerformed(R820TTunerEditor.java:242)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor.setItem(R820TTunerEditor.java:590)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerEditor.setItem(R820TTunerEditor.java:55)
        at io.github.dsheirer.source.tuner.TunerEditor.setTunerConfiguration(TunerEditor.java:376)
        at io.github.dsheirer.source.tuner.TunerEditor$2.valueChanged(TunerEditor.java:151)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
        at java.desktop/javax.swing.JTable.setRowSelectionInterval(Unknown Source)
        at io.github.dsheirer.source.tuner.TunerEditor.setItem(TunerEditor.java:298)
        at io.github.dsheirer.source.tuner.TunerViewPanel$1.valueChanged(TunerViewPanel.java:107)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by jimmid709** [comment]
I am having the java usb error 9 controlling the dongles too on my windows 11 computer too in sdr trunk.  I also got a usb error 9 while trying to turn on Biastee in the command prompt for Sdr sharp.   Programs read the rtl-sdr dongles, but the problem occurs going the other way when trying to control/change them.

2023-11-22 16:00:09.861 INFO  i.g.dsheirer.gui.SDRTrunk - starting main application gui  [30MB/60MB 50%]
2023-11-22 16:00:34.356 ERROR i.g.d.s.t.m.PolyphaseChannelSourceManager - Error getting source  [100MB/288MB 35%]

org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error

        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.write(RTL2832TunerController.java:825)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeDemodRegister(RTL2832TunerController.java:710)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.enableI2CRepeater(RTL2832TunerController.java:605)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController$ControllerAdapter.enableI2CRepeater(RTL2832TunerController.java:1552)
        at io.github.dsheirer.source.tuner.rtl.r8x.r820t.R820TEmbeddedTuner.setTunedFrequency(R820TEmbeddedTuner.java:75)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.setTunedFrequency(RTL2832TunerController.java:143)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:203)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:175)
        at io.github.dsheirer.source.tuner.TunerController.setFrequency(TunerController.java:261)
        at io.github.dsheirer.source.tuner.manager.PolyphaseChannelSourceManager.getSource(PolyphaseChannelSourceManager.java:454)
        at io.github.dsheirer.source.tuner.manager.TunerManager.getSource(TunerManager.java:607)
        at io.github.dsheirer.source.tuner.manager.TunerManager.getSource(TunerManager.java:533)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.startProcessing(ChannelProcessingManager.java:382)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.start(ChannelProcessingManager.java:303)
        at io.github.dsheirer.gui.playlist.channel.ChannelConfigurationEditor.lambda$getPlayButton$3(ChannelConfigurationEditor.java:373)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-11-22 16:00:34.358 ERROR i.g.d.g.p.c.ChannelConfigurationEditor - Error starting channel [Far West Ambo] - No Tuner Available  [100MB/288MB 35%]

Any fix yet?
