### ISSUE TITLE
NPE thrown on startup for Channel with empty alias list name

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#73]
Astrak's Avatar     

SDRTrunk java error
I am getting this message after loading the USB devices
Exception in thread "main" java.lang.NullPointerException
at alias.AliasDirectory.getAliasList(Unknown Source)
at controller.channel.Channel.setupProcessingChain(Un known Source)
at controller.channel.Channel.setup(Unknown Source)
at controller.channel.Channel.start(Unknown Source)
at controller.channel.Channel.enableChanged(Unknown Source)
at controller.channel.Channel.setResourceManager(Unkn own Source)
at controller.channel.ChannelNode.init(Unknown Source)
at controller.site.SiteNode.init(Unknown Source)
at controller.system.SystemNode.init(Unkown Source)
at controller.system.SystemListNode.init(Unknown Source)
at playlist.PlaylistNode.init(Unknown Source)
at playlist.PlaylistNode.loadPlaylist(Unknown Source)
at controller.ConfigurationControllerModel.init(Unkno wn Source)
at gui.SDRTrunk.initGUI(Unknown Source)
at gui.SDRTrunk.<init>(Unknown Source)
at gui.SDRTrunk.main(Unknown Source)
## Any help would be appreciated.

The issue is in the alias list lookup.  Add null alias list name checker to the lookup method.

**Comment by DSheirer** [comment]
I'm not planning to release a build 0.2.1 since build 0.3.0 is about ready to enter beta testing.  This issue won't be fixed.
