### ISSUE TITLE
Trying to run sdrtrunk on ubuntu 12.04 NO-PAE x86

### ISSUE THREAD

**Issue by StaRipper** [DSheirer/sdrtrunk#752]
xxx@ubuntu:~/Downloads/sdr-trunk-linux-x86_32-v0.4.0/bin$ ./sdr-trunk
16:40:47.418 INFO  i.g.d.log.ApplicationLog - Application Log File: /home/xxx/SDRTrunk/logs/sdrtrunk_app.log  [5MB/11MB 43%]
16:40:47.754 INFO  i.g.d.log.ApplicationLog -   [5MB/11MB 50%]
16:40:47.761 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/11MB 50%]
16:40:47.762 INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [5MB/11MB 50%]
16:40:47.762 INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [5MB/11MB 50%]
16:40:47.764 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [5MB/11MB 50%]
16:40:47.768 INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [5MB/11MB 50%]
16:40:47.769 INFO  i.g.d.log.ApplicationLog - Host OS Name:          Linux  [5MB/11MB 50%]
16:40:47.797 INFO  i.g.d.log.ApplicationLog - Host OS Arch:          i386  [5MB/11MB 50%]
16:40:47.812 INFO  i.g.d.log.ApplicationLog - Host OS Version:       3.2.0-126-generic  [5MB/11MB 50%]
16:40:47.813 INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        1  [5MB/11MB 50%]
16:40:47.829 INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  181 MB  [5MB/11MB 50%]
16:40:47.829 INFO  i.g.d.log.ApplicationLog - Storage Directories:  [5MB/11MB 50%]
16:40:47.833 INFO  i.g.d.log.ApplicationLog -  Application Root: /home/xxx/SDRTrunk  [5MB/11MB 50%]
16:40:47.834 INFO  i.g.d.log.ApplicationLog -  Application Log:  /home/xxx/SDRTrunk/logs  [5MB/11MB 50%]
16:40:47.847 INFO  i.g.d.log.ApplicationLog -  Event Log:        /home/xxx/SDRTrunk/event_logs  [5MB/11MB 50%]
16:40:47.857 INFO  i.g.d.log.ApplicationLog -  Playlist:         /home/xxx/SDRTrunk/playlist  [5MB/11MB 51%]
16:40:47.869 INFO  i.g.d.log.ApplicationLog -  Recordings:       /home/xxx/SDRTrunk/recordings  [5MB/11MB 51%]
16:40:48.852 INFO  i.g.d.util.ThreadPool - Application thread pool created with [2] threads  [6MB/11MB 56%]
16:40:48.853 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /home/xxx/SDRTrunk  [6MB/11MB 56%]
16:40:48.868 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/home/xxx/SDRTrunk/SDRTrunk.properties]  [6MB/11MB 57%]
16:40:48.870 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/home/xxx/SDRTrunk/SDRTrunk.properties]  [6MB/11MB 57%]
OpenJDK Server VM warning: You have loaded library /home/xxx/.openjfx/cache/13.0.1/libprism_es2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/xxx/.openjfx/cache/13.0.1/libprism_es2.so: /home/xxx/.openjfx/cache/13.0.1/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AMD 64 .so on a IA 32 platform)
java.lang.UnsatisfiedLinkError: /home/xxx/.openjfx/cache/13.0.1/libprism_es2.so: /home/xxx/.openjfx/cache/13.0.1/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AMD 64 .so on a IA 32 platform)
    at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
    at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
    at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
    at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
    at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.base/java.lang.Runtime.load0(Unknown Source)
    at java.base/java.lang.System.load(Unknown Source)
    at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
    at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
    at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    at java.base/java.lang.Thread.run(Unknown Source)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /home/xxx/.openjfx/cache/13.0.1/libprism_sw.so: /home/xxx/.openjfx/cache/13.0.1/libprism_sw.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AMD 64 .so on a IA 32 platform)
java.lang.UnsatisfiedLinkError: /home/xxx/.openjfx/cache/13.0.1/libprism_sw.so: /home/xxx/.openjfx/cache/13.0.1/libprism_sw.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AMD 64 .so on a IA 32 platform)
    at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
    at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
    at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
    at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
    at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.base/java.lang.Runtime.load0(Unknown Source)
    at java.base/java.lang.System.load(Unknown Source)
    at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
    at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
    at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    at java.base/java.lang.Thread.run(Unknown Source)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
    at javafx.scene.text.Font.getDefaultSystemFontSize(Font.java:95)
    at javafx.scene.text.Font.loadFont(Font.java:542)
    at jiconfont.javafx.IconFontFX.register(IconFontFX.java:43)
    at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:167)
    at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:668)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: No toolkit found
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
    at javafx.scene.text.Font.getDefaultSystemFontSize(Font.java:95)
    at javafx.scene.text.Font.loadFont(Font.java:542)
    at jiconfont.javafx.IconFontFX.register(IconFontFX.java:43)
    at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:167)
    at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:668)
xxx@ubuntu:~/Downloads/sdr-trunk-linux-x86_32-v0.4.0/bin$

Something about openjfx?

**Comment by StaRipper** [comment]
Hi Denny,
Saw your answer on the Google Groups
Waiting  for a x86 working build.

Your Answer: 
"There's a problem with the 32-bit versions of sdrtrunk.  The bundled JavaFX libraries were compiled with a 64-bit compiler, making them incompatible with the 32-bit JVM.

I'm going to pull both of the 32-bit versions until the next release, when I can get the issue resolved.

Denny"
