### ISSUE TITLE
Icecast 2.4.4 no audio stream/ 5.0 alpha

### ISSUE THREAD

**Issue by cspencer49519** [DSheirer/sdrtrunk#771]
Running under MacOS Catalina. Audio streaming to my Icecast server was working fine on the 4/final build. I do notice the following error when attempting to add all the aliases for the system I'm monitoring through the channel editor.

18:38:47.722 ERROR i.g.d.p.PlaylistManager - IO error while writing the playlist to a file [/Users/graffix/SDRTrunk/playlist/default.xml]  [510MB/752MB 67%]
com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: io.github.dsheirer.playlist.PlaylistV2["alias"]->java.util.Collections$UnmodifiableRandomAccessList[3494]->io.github.dsheirer.alias.Alias["id"]->com.sun.javafx.collections.ObservableListWrapper[2])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:153)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:107)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3176)
	at io.github.dsheirer.playlist.PlaylistManager.save(PlaylistManager.java:428)
	at io.github.dsheirer.playlist.PlaylistManager$PlaylistSaveTask.run(PlaylistManager.java:565)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.AbstractList$Itr.checkForComodification(AbstractList.java:399)
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:368)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:129)
	... 22 common frames omitted

**Comment by n2cr** [comment]
Latest commit has this working for me under Ubuntu VM.  Wasn't working with last weekend's code.
