### ISSUE TITLE
After exiting sleep, the sound disappears  0.4.0

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#782]
After the computer wakes up from sleep mode, sdrtrunk loses connection with the sound device. If you change the device in the settings and then return it back, a sound will appear and the following code will be displayed in the terminal:

```
19:49:43.799 ERROR i.g.d.a.p.AudioOutput - Error while processing audio buffers  [258MB/519MB 49%]
java.lang.NullPointerException: null
	at io.github.dsheirer.audio.playback.AudioOutput.processAudio(AudioOutput.java:492)
	at io.github.dsheirer.audio.playback.AudioOutput$AudioSegmentProcessor.run(AudioOutput.java:738)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
19:49:44.079 ERROR i.g.d.a.p.AudioOutput - Error while processing audio buffers  [284MB/519MB 54%]
java.lang.NullPointerException: null
	at io.github.dsheirer.audio.playback.AudioOutput.processAudio(AudioOutput.java:492)
	at io.github.dsheirer.audio.playback.AudioOutput$AudioSegmentProcessor.run(AudioOutput.java:738)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
Sound does not always disappear after leaving sleep, but often it still disappears.

**Comment by ah1102** [comment]
It got better, but sometimes the sound disappears anyway. Appears when switching an audio device in sdrtrunk settings.

**Comment by ah1102** [comment]
Only in the terminal now it writes nothing.
