### ISSUE TITLE
Unable to get device list from libusb

### ISSUE THREAD

**Issue by rwebb3** [DSheirer/sdrtrunk#897]
I can't launch the application. 
[sdrtrunk_app.log](https://github.com/DSheirer/sdrtrunk/files/4995225/sdrtrunk_app.log)

after the last line in the log Java throws this exception: 
```
Exception in thread "main" java.lang.IllegalStateException: deviceListPointer is not initialized
        at org.usb4java.LibUsb.freeDeviceList(Native Method)
        at io.github.dsheirer.source.tuner.TunerManager.initTuners(TunerManager.java:188)
        at io.github.dsheirer.source.tuner.TunerManager.<init>(TunerManager.java:79)
        at io.github.dsheirer.source.SourceManager.<init>(SourceManager.java:46)
        at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:167)
        at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:624)
```

Any ideas?

**Comment by rwebb3** [comment]
sorry. I found the support form. I'll post there.
