### ISSUE TITLE
USB Error 9 Error Writing Byte Buffer

### ISSUE THREAD

**Issue by simplio** [DSheirer/sdrtrunk#917]
I was browsing the web while listening to the local APCO sites and I noticed a slight audio hiccup. This doesn't seem to hamper operation. I really don't know what it means but I thought I should report this error, SDRTrunk v0.5.0alpha3

Two RTLSDR's in use.

org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.write(RTL2832TunerController.java:823)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeDemodRegister(RTL2832TunerController.java:719)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.enableI2CRepeater(RTL2832TunerController.java:623)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerController.setTunedFrequency(R820TTunerController.java:185)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:181)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:153)
        at io.github.dsheirer.source.tuner.TunerController.setFrequency(TunerController.java:199)
        at io.github.dsheirer.source.tuner.manager.PolyphaseChannelSourceManager.getSource(PolyphaseChannelSourceManager.java:433)
        at io.github.dsheirer.source.tuner.TunerModel.getSource(TunerModel.java:463)
        at io.github.dsheirer.source.SourceManager.getSource(SourceManager.java:91)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.startProcessing(ChannelProcessingManager.java:300)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.receive(ChannelProcessingManager.java:182)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.receive(ChannelProcessingManager.java:70)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.broadcast(P25TrafficChannelManager.java:595)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processPhase2ChannelGrant(P25TrafficChannelManager.java:522)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processChannelGrant(P25TrafficChannelManager.java:244)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processChannelGrant(P25P1DecoderState.java:312)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBKGroupVoiceChannelGrant(P25P1DecoderState.java:1912)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBK(P25P1DecoderState.java:1095)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:287)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:148)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:103)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:96)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:95)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:37)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.dispatchMessage(P25P1MessageFramer.java:326)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:205)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:71)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:58)
        at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:115)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:89)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:122)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:48)
        at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:42)
        at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:23)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.flush(ReusableComplexBufferAssembler.java:158)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:132)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:144)
        at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:97)
        at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.processChannelResults(ChannelOutputProcessor.java:124)
        at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.processSamples(PolyphaseChannelSource.java:248)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource$ScheduledIntervalProcessor.run(TunerChannelSource.java:321)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by simplio** [comment]
then DDC errors showed up for the first time:
09:15:57.276 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [312MB/938MB 33%]
09:15:57.625 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [399MB/938MB 42%]
09:15:57.726 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [431MB/938MB 45%]
09:15:57.776 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [441MB/938MB 47%]
09:15:57.926 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [484MB/938MB 51%]
09:15:58.026 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [505MB/938MB 53%]
09:15:58.126 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [537MB/938MB 57%]
09:15:58.225 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [559MB/938MB 59%]
09:15:58.326 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [583MB/938MB 62%]
09:15:58.376 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [602MB/938MB 64%]
09:15:58.526 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [634MB/938MB 67%]
09:15:58.626 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [667MB/938MB 71%]
09:15:58.676 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [678MB/938MB 72%]
09:15:58.826 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [720MB/938MB 76%]
09:15:58.927 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [742MB/938MB 79%]
09:15:59.026 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [216MB/938MB 23%]
09:15:59.125 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [237MB/938MB 25%]
09:15:59.226 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [261MB/938MB 27%]
09:15:59.325 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [290MB/938MB 30%]
09:15:59.426 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [312MB/938MB 33%]
09:15:59.526 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [344MB/938MB 36%]
09:15:59.576 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [355MB/938MB 37%]
09:15:59.726 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [397MB/938MB 42%]
09:15:59.826 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [419MB/938MB 44%]
09:15:59.877 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [430MB/938MB 45%]
09:16:00.025 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [473MB/938MB 50%]
09:16:00.125 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [495MB/938MB 52%]
09:16:00.227 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [526MB/938MB 56%]
09:16:00.326 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [548MB/938MB 58%]
09:16:00.425 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:852900000 (852893750-852906250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [580MB/938MB 61%]
09:16:01.776 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [375MB/938MB 40%]
09:16:01.826 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [387MB/938MB 41%]
09:16:02.226 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [494MB/938MB 52%]
09:16:02.276 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [505MB/938MB 53%]
09:16:02.426 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [547MB/938MB 58%]
09:16:02.525 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [568MB/938MB 60%]
09:16:02.578 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [580MB/938MB 61%]
09:16:02.725 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [622MB/938MB 66%]
09:16:02.825 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [644MB/938MB 68%]
09:16:02.926 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [676MB/938MB 72%]
09:16:03.026 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [699MB/938MB 74%]
09:16:03.125 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [730MB/938MB 77%]
09:16:03.177 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [741MB/938MB 79%]
09:16:03.326 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [226MB/938MB 24%]
09:16:03.425 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [247MB/938MB 26%]
09:16:03.475 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [258MB/938MB 27%]
09:16:03.476 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [259MB/938MB 27%]
09:16:03.576 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [290MB/938MB 30%]
09:16:03.577 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [290MB/938MB 30%]
09:16:03.676 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [312MB/938MB 33%]
09:16:03.676 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [312MB/938MB 33%]
09:16:03.826 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [355MB/938MB 37%]
09:16:03.826 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [355MB/938MB 37%]
09:16:03.878 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [366MB/938MB 39%]
09:16:03.879 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [366MB/938MB 39%]
09:16:04.025 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [408MB/938MB 43%]
09:16:04.076 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [419MB/938MB 44%]
09:16:04.176 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [440MB/938MB 46%]
09:16:04.326 INFO  i.g.d.d.f.c.PolyphaseChannelManager - Can't provide DDC for Channel:853300000 (853293750-853306250) due to channelizer frequency [8.519625E8] and sample rate [1600000.0]  [485MB/938MB 51%]
09:16:08.437 ERROR i.g.d.s.tuner.TunerModel - Error obtaining channel from tuner [RTL2832 SDR/R820T 00000001]  [440MB/938MB 46%]
org.usb4java.LibUsbException: USB error 9: error writing byte buffer: Pipe error
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.write(RTL2832TunerController.java:823)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.writeDemodRegister(RTL2832TunerController.java:719)
        at io.github.dsheirer.source.tuner.rtl.RTL2832TunerController.enableI2CRepeater(RTL2832TunerController.java:623)
        at io.github.dsheirer.source.tuner.rtl.r820t.R820TTunerController.setTunedFrequency(R820TTunerController.java:185)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:181)
        at io.github.dsheirer.source.tuner.frequency.FrequencyController.setFrequency(FrequencyController.java:153)
        at io.github.dsheirer.source.tuner.TunerController.setFrequency(TunerController.java:199)
        at io.github.dsheirer.source.tuner.manager.PolyphaseChannelSourceManager.getSource(PolyphaseChannelSourceManager.java:433)
        at io.github.dsheirer.source.tuner.TunerModel.getSource(TunerModel.java:463)
        at io.github.dsheirer.source.SourceManager.getSource(SourceManager.java:91)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.startProcessing(ChannelProcessingManager.java:300)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.receive(ChannelProcessingManager.java:182)
        at io.github.dsheirer.controller.channel.ChannelProcessingManager.receive(ChannelProcessingManager.java:70)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.broadcast(P25TrafficChannelManager.java:595)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processPhase2ChannelGrant(P25TrafficChannelManager.java:522)
        at io.github.dsheirer.module.decode.p25.P25TrafficChannelManager.processChannelGrant(P25TrafficChannelManager.java:244)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processChannelGrant(P25P1DecoderState.java:312)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBKGroupVoiceChannelGrant(P25P1DecoderState.java:1912)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.processTSBK(P25P1DecoderState.java:1095)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:287)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderState.receive(P25P1DecoderState.java:148)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:103)
        at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:96)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:95)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageProcessor.receive(P25P1MessageProcessor.java:37)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.dispatchMessage(P25P1MessageFramer.java:326)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:205)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1MessageFramer.receive(P25P1MessageFramer.java:71)
        at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:58)
        at io.github.dsheirer.dsp.psk.DQPSKGardnerDemodulator.calculateSymbol(DQPSKGardnerDemodulator.java:88)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:115)
        at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:89)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:122)
        at io.github.dsheirer.module.decode.p25.phase1.P25P1DecoderLSM.receive(P25P1DecoderLSM.java:48)
        at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:42)
        at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:23)
        at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.flush(ReusableComplexBufferAssembler.java:158)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:132)
        at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:144)
        at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:97)
        at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.processChannelResults(ChannelOutputProcessor.java:124)
        at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.processSamples(PolyphaseChannelSource.java:248)
        at io.github.dsheirer.source.tuner.channel.TunerChannelSource$ScheduledIntervalProcessor.run(TunerChannelSource.java:321)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by simplio** [comment]
Exiting SDRTrunk and relaunching it clears the error. It happened switching sites by turning one off and the other on or turning all sites off and turning one on in Channels in the Playlist editor.

**Comment by simplio** [comment]
Its not repeating. Restarting SDRTrunk clears the error. using two dongles and its taking up the only 2 usb ports the laptop has. It's usually fine. Thanks Denny.
