### ISSUE TITLE
Duplicte Call Detection Causes Out Of Memory Errors

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#945]
New logging added to the duplicate call detector runnable indicates that the problem that is causing the duplicate call detector to fail is a concurrent modification exception.

Note: add protective code to ensure that the in-memory buffer used for gather call events is bounded so that it can't grow and cause out of memory crash.

15:46:53.420 ERROR i.g.d.a.DuplicateCallDetector - Unknown error while processing audio segments for duplicate call detection.  Please report this to the developer.  [2GB/3GB 77%]
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.base/java.util.ArrayList$Itr.next(Unknown Source)
        at io.github.dsheirer.identifier.IdentifierCollection.getIdentifiers(IdentifierCollection.java:178)
        at io.github.dsheirer.audio.DuplicateCallDetector$SystemDuplicateCallDetector.isDuplicate(DuplicateCallDetector.java:144)
        at io.github.dsheirer.audio.DuplicateCallDetector$SystemDuplicateCallDetector.process(DuplicateCallDetector.java:271)
        at io.github.dsheirer.audio.DuplicateCallDetector$SystemDuplicateCallDetector.lambda$startMonitoring$0(DuplicateCallDetector.java:116)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DSheirer** [comment]
Resolved in alpha 4.
